import {useEffect,useState} from 'react';
import {Panel} from '../../../web/src/components/presentational';
import type {ConflictService,ConflictRecord,ConflictDocument} from './conflicts';
const text=(value:unknown)=>typeof value==='string'?value:JSON.stringify(value??null,null,2);
const labels:Record<string,string>={title:'标题',content:'笔记正文',observation:'观察',objective:'本次目标',is_highlighted:'星标',highlight_type:'星标类型',highlight_note:'星标说明',run_type:'记录类型',status:'运行状态',scientific_outcome:'科研结果',context_data:'高级语境'};
export function ConflictPanel({service,project,refreshToken,refresh}:{service:ConflictService;project:string;refreshToken:unknown;refresh:()=>Promise<void>}){
 const [records,setRecords]=useState<ConflictRecord[]>([]),[selected,setSelected]=useState<ConflictRecord|null>(null),[inputs,setInputs]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState<string[]>([]),[types,setTypes]=useState<Record<string,string>>({});
 const read=async()=>setRecords(await service.list(project));
 useEffect(()=>{let active=true;void service.list(project).then(r=>{if(active)setRecords(r);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[service,project,refreshToken]);
 function compare(r:ConflictRecord){setSelected(structuredClone(r));const fields=[...new Set(r.trusted.candidates.flatMap(c=>Object.keys(c.document)))],values:Record<string,string>={},kinds:Record<string,string>={},confirmed:string[]=[];
  for(const field of fields){const all=r.trusted.candidates.map(c=>c.document[field]);const same=all.every(v=>JSON.stringify(v)===JSON.stringify(all[0]));values[field]=same?text(all[0]):'';kinds[field]=typeof all.find(v=>v!==null&&v!==undefined);if(same)confirmed.push(field);}
  setInputs(values);setTypes(kinds);setReviewed(confirmed);setError('');setNotice('比较版本已冻结；请逐字段选择分支或填写提案，新分支或本地修改会阻止提交。');}
 function selectValue(field:string,value:unknown){setInputs(old=>({...old,[field]:text(value)}));setTypes(old=>({...old,[field]:value===null?'null':typeof value}));setReviewed(old=>[...new Set([...old,field])]);}

 async function submit(){if(!selected)return;setBusy(true);setError('');try{const document:ConflictDocument={};for(const [k,v] of Object.entries(inputs)){document[k]=types[k]==='string'?v:JSON.parse(v);}await service.resolve(selected,document);setNotice('提案已保存到本机：CANDIDATE，待人工批准。冲突收束不等于已接受。');await read();await refresh();setSelected(null);}catch(e){setError(`${String(e)}；输入已保留。请重新比较当前版本后明确选择。`);}finally{setBusy(false);}}
 return <Panel title="冲突与候选"><div className="qa-content"><p>历史对端回执仅说明当时已应用；下列状态表示当前候选，尚未获得人工批准。</p>{records.length===0?<p>没有待比较的冲突或候选。</p>:records.map(r=><div key={r.object_id}><span>{String(r.trusted.candidates[0]?.document.title??r.object_id)} · {r.trusted.status==='conflicted'?`${r.trusted.heads.length} 个分支`:'CANDIDATE · 待人工批准'}</span> <button disabled={busy} onClick={()=>compare(r)}>比较 {r.object_id}</button></div>)}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{selected&&<section aria-label="字段三方比较"><p>对象 {selected.object_id} · {selected.trusted.base_revision?'共同 BASE '+selected.trusted.base_revision:'无唯一共同基线'}</p><p>分支按设备标识区分；所有分支均保留。</p><fieldset disabled={busy}>{Object.keys(inputs).map(field=><div key={field}><h3>{labels[field]??field}</h3><p>共同 BASE</p><pre>{selected.trusted.base?text(selected.trusted.base[field]):'无唯一共同基线'}</pre>{selected.trusted.candidates.map(c=><div key={c.revision}><p>{c.device_id===selected.local_device_id?'本地分支':'远端分支'} · 设备 {c.device_id} · {c.state}</p><pre>{text(c.document[field])}</pre><button onClick={()=>selectValue(field,c.document[field])}>采用{c.device_id===selected.local_device_id?'本地':'远端'} {labels[field]??field} · {c.revision.slice(0,8)}</button></div>)}<label>{labels[field]??field}提案<textarea aria-label={`${labels[field]??field}提案`} rows={3} value={inputs[field]} onChange={e=>{setInputs(old=>({...old,[field]:e.target.value}));setReviewed(old=>[...new Set([...old,field])]);}}/></label></div>)}</fieldset><button disabled={busy||Object.keys(inputs).some(k=>!reviewed.includes(k))} onClick={()=>void submit()}>保存离线提案（待人工批准）</button><details><summary>工作副本与审计</summary><pre>{JSON.stringify({work:selected.work,pending:selected.pending,audit:selected.audit},null,2)}</pre></details></section>}</div></Panel>;
}
