// Explicit TEST ONLY build entry. This fixture supplies no real trust, key, nonce or network authorization.
import {digest} from '../../../../packages/sync-protocol/src/browser';
import {openLocalDatabase} from '../local/db';
import {LocalCommandService} from '../local/commands';
import {StableWireAdapter,type BindingRecord} from './wire';
const open=()=>openLocalDatabase('researchhub-browser-sync-qa-business-v1');
const commands=new LocalCommandService(open,'researchhub-browser-sync-qa-changes-v1',true);
const adapter=new StableWireAdapter(open,true);
async function install(){const s=await commands.snapshot();for(const p of s.projects){const record:BindingRecord={id:`binding:${p.id}`,state:'TEST_ONLY',generation:1,binding:{binding_version:1,semantic_project_id:p.id,opaque_project_id:crypto.randomUUID(),module_snapshot:p.module_snapshot,module_snapshot_hash:await digest(p.module_snapshot),local_module_hash:{algorithm:'sha256-json-stringify',value:p.module_hash},capabilities:{protocol_version:2,schema_version:2,object_types:['ResearchRun','Note']},principal_map:[],principal:{device_id:crypto.randomUUID(),actor_id:crypto.randomUUID(),actor_type:'human',role:'writer'},trust:{membership_epoch:1,key_epoch:1,manifest_head:'1'.repeat(64),owner_root:'2'.repeat(64),recovery_root:'3'.repeat(64),manifest_chain:[{TEST_ONLY:true}]}}};record.binding.principal_map=[record.binding.principal];const db=await open();await new Promise<void>((ok,no)=>{const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(record);tx.oncomplete=()=>ok();tx.onabort=()=>no(tx.error);});db.close();}}
async function metadata(){const db=await open();return new Promise<any[]>((ok,no)=>{const tx=db.transaction('meta');let value:any[];tx.objectStore('meta').getAll().onsuccess=e=>value=(e.target as IDBRequest).result;tx.oncomplete=()=>{db.close();ok(value);};tx.onabort=()=>{db.close();no(tx.error);};});}
document.querySelector('.qa-banner')?.append(' · TEST ONLY fixture build，未配对');
(window as any).__SYNC_QA_TEST_ONLY__={label:'TEST ONLY - NOT PAIRED',race:async(id:string)=>{let entered=0;let release!:()=>void;const gate=new Promise<void>(ok=>release=ok);const afterPrepared=async()=>{if(++entered===2)release();await gate;};return Promise.allSettled([adapter.convert(id,{afterPrepared}),adapter.convert(id,{afterPrepared})]);},install,commands,metadata,convert:(id:string,fault?:'afterPrepared'|'abortCommit')=>adapter.convert(id,fault==='afterPrepared'?{afterPrepared:async()=>{throw Error('TEST ONLY interrupted after preparation');}}:{abortCommit:fault==='abortCommit'}),normalConvert:(id:string)=>new StableWireAdapter(open).convert(id)};
