import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {resolve} from 'node:path';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {runtime,origin,startServer,stopServer,launch} from './lifecycle';
const snapshot=(p:Page)=>p.evaluate(()=> (window as any).__LOCAL_QA__.snapshot());
const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
function resign(pack:any){pack.digest=createHash('sha256').update(canonical(pack.content)).digest('hex');return pack;}
async function preview(p:Page,pack:any){await p.getByLabel('选择合成救援包').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pack))});}
async function download(p:Page){const wait=p.waitForEvent('download');await p.getByRole('button',{name:'导出合成救援包',exact:true}).click();const file=await wait;const path=resolve(runtime,'synthetic-rescue-'+Date.now()+'.json');await file.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
async function diagnostics(p:Page){await p.getByText('诊断与合成草稿救援',{exact:true}).click();}
async function capture(context:BrowserContext){for(const p of context.pages().filter(p=>p.url().startsWith(origin))){await p.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();scrollTo(0,0);});await p.screenshot({path:resolve(runtime,`task3-attempt-${Date.now()}-${context.pages().indexOf(p)}.png`),fullPage:true});}}
test('明文救援：新 profile、预览、原子恢复、幂等、冲突与严格拒绝',async()=>{
 const server=await startServer();const contexts:BrowserContext[]=[];
 try{
 const source=await launch(resolve(runtime,'profiles',`rescue-source-${Date.now()}`));contexts.push(source);const p=await source.newPage();await p.goto(origin);await p.getByRole('button',{name:'初始化合成工作区',exact:true}).click();await expect(p.getByLabel('项目选择')).toBeVisible();
 await p.getByRole('button',{name:'新建 Run',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill('SYNTHETIC 星标');await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');await p.getByRole('button',{name:'设为星标',exact:true}).click();await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');
 await p.getByRole('button',{name:'新建 Note',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill('SYNTHETIC Note');await p.getByLabel('笔记正文').fill('已保存的合成观察');await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');await p.getByLabel('笔记正文').fill('未保存也能救援');
 await p.evaluate(async()=>{const db=await new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('researchhub-synthetic-local-v1');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});await new Promise<void>((ok,no)=>{const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put({id:'TEST-ONLY-forbidden-probe',private_key:'DUMMY SYNTHETIC NOT A KEY',nonce_ledger:'DUMMY',token:'DUMMY'});tx.oncomplete=()=>ok();tx.onabort=()=>no(tx.error);});db.close();});const before=await snapshot(p);await diagnostics(p);await expect(p.getByText(/明文.*仅合成 QA/)).toBeVisible();const pack=await download(p);expect(pack.content.drafts).toHaveLength(1);expect(pack.content.drafts[0].body).toBe('未保存也能救援');expect(pack.content).not.toHaveProperty('identity');expect(JSON.stringify(pack)).not.toContain('DUMMY');expect(await snapshot(p)).toEqual(before);
 const target=await launch(resolve(runtime,'profiles',`rescue-target-${Date.now()}`));contexts.push(target);const q=await target.newPage();await q.goto(origin);await diagnostics(q);const empty=await snapshot(q);await preview(q,pack);await expect(q.getByTestId('rescue-preview')).toContainText('2 条记录');expect(await snapshot(q)).toEqual(empty);await q.evaluate(()=>{const original=IDBObjectStore.prototype.add;let once=true;IDBObjectStore.prototype.add=function(...args:any[]){const r=original.apply(this,args as any);if(once&&this.name==='audit'&&args[0]?.event==='restore'){once=false;r.addEventListener('success',()=>this.transaction.abort());}return r;};});await q.getByRole('button',{name:'确认恢复到空工作区',exact:true}).click();await expect(q.getByTestId('rescue-error')).toContainText('未提交');expect(await snapshot(q)).toEqual(empty);await q.getByRole('button',{name:'确认恢复到空工作区',exact:true}).click();await expect(q.getByTestId('rescue-status')).toContainText('恢复已提交');await expect(q.getByRole('button',{name:'初始化合成工作区',exact:true})).toHaveCount(0);
 const restored=await snapshot(q);expect(restored.objects).toEqual(before.objects);expect(restored.operations).toEqual(before.operations);expect(restored.audit.filter((a:any)=>a.event!=='restore')).toEqual(before.audit);expect(restored.audit.filter((a:any)=>a.event==='restore')).toHaveLength(1);expect(restored.identity.device_id).not.toBe(before.identity.device_id);expect(restored.identity.workspace_id).not.toBe(before.identity.workspace_id);expect(restored.audit.find((a:any)=>a.event==='restore').source.device_id).toBe(restored.identity.device_id);
 await preview(q,pack);await q.getByRole('button',{name:'确认恢复到空工作区',exact:true}).click();await expect(q.getByTestId('rescue-status')).toContainText('已恢复过');expect(await snapshot(q)).toEqual(restored);
 const conflict=structuredClone(pack);conflict.content.objects[0].title='ID 相同内容不同';for(const op of conflict.content.operations)if(op.object_id===conflict.content.objects[0].id)op.payload.title=conflict.content.objects[0].title;await preview(q,resign(conflict));await q.getByRole('button',{name:'确认恢复到空工作区',exact:true}).click();await expect(q.getByTestId('rescue-error')).toContainText('冲突');expect(await snapshot(q)).toEqual(restored);
 for(const mutate of [(x:any)=>{x.digest='0'.repeat(64);},(x:any)=>{x.content.private_key='TEST ONLY forbidden';resign(x);},(x:any)=>{x.content.operations[0].payload.token='TEST ONLY';resign(x);},(x:any)=>{x.content.projects[0].module_snapshot.private_key='TEST ONLY';resign(x);}]){const bad=structuredClone(pack);mutate(bad);await preview(q,bad);await expect(q.getByTestId('rescue-error')).toBeVisible();await expect(q.getByRole('button',{name:'确认恢复到空工作区',exact:true})).toBeDisabled();expect(await snapshot(q)).toEqual(restored);}
 await q.getByRole('button',{name:'打开救援草稿为新草稿',exact:true}).click();await expect(q.getByLabel('笔记正文')).toHaveValue('未保存也能救援');await expect(q.getByTestId('local-save')).toContainText('尚未保存');expect(await snapshot(q)).toEqual(restored);await q.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(q.getByTestId('local-save')).toHaveText('已保存到本机');expect((await snapshot(q)).objects).toHaveLength(3);
 await preview(q,pack);await expect(q.getByTestId('rescue-preview')).toBeVisible();await q.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();scrollTo(0,0);});await q.screenshot({path:resolve(runtime,'rescue-desktop.png'),fullPage:true});await q.setViewportSize({width:390,height:844});await q.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();scrollTo(0,0);});await q.screenshot({path:resolve(runtime,'rescue-mobile.png'),fullPage:true});
 }finally{for(const c of contexts){try{await capture(c);}finally{await c.close();}}await stopServer(server);}
});

test('TEST ONLY 配额与持久化拒绝保留输入，真实升级阻塞可解除',async()=>{
 const server=await startServer();const context=await launch(resolve(runtime,'profiles',`storage-${Date.now()}`));
 try{const p=await context.newPage();await p.goto(origin);await p.getByRole('button',{name:'初始化合成工作区',exact:true}).click();await p.getByRole('button',{name:'新建 Note',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill('SYNTHETIC 已保存待处理记录');await p.getByLabel('笔记正文').fill('故障不能删除此待处理操作');await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');const queued=await snapshot(p);expect(queued.operations.length).toBeGreaterThan(0);expect(queued.operations.every((op:any)=>op.state==='pending')).toBe(true);await p.getByRole('button',{name:'新建 Note',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill('配额失败草稿');await p.getByLabel('笔记正文').fill('保留唯一输入');await diagnostics(p);await p.getByText('TEST ONLY 故障探针',{exact:true}).click();const before=await snapshot(p);await p.getByRole('button',{name:'TEST ONLY：下次保存配额失败',exact:true}).click();await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('本次修改未保存');await expect(p.getByRole('alert')).toContainText('QuotaExceededError');await expect(p.getByLabel('笔记正文')).toHaveValue('保留唯一输入');expect(await snapshot(p)).toEqual(before);expect((await download(p)).content.drafts[0].body).toBe('保留唯一输入');
 await p.getByRole('button',{name:'TEST ONLY：模拟持久化拒绝',exact:true}).click();await expect(p.getByTestId('storage-status')).toContainText('TEST ONLY');await expect(p.getByTestId('storage-status')).toContainText('拒绝');await p.getByRole('button',{name:'TEST ONLY：模拟 API 不支持',exact:true}).click();await expect(p.getByTestId('storage-status')).toContainText('不支持');const transportRejection=await p.evaluate(async()=>{try{await (window as any).__LOCAL_QA__.testOnlyTransportProbe();return 'unexpected success';}catch(e){return String(e);}});expect(transportRejection).toContain('TEST ONLY：模拟连接失败');await p.getByRole('button',{name:'TEST ONLY：模拟连接失败',exact:true}).click();await expect(p.getByTestId('transport-probe')).toContainText('TEST ONLY');await expect(p.getByTestId('transport')).toContainText('not_configured');expect(await snapshot(p)).toEqual(before);
 await p.getByRole('button',{name:'申请持久存储并刷新估计',exact:true}).click();await expect(p.getByTestId('storage-status')).toContainText('使用量估计');await expect(p.getByTestId('storage-status')).not.toContainText('TEST ONLY');
 await p.evaluate(()=>{const original=IDBFactory.prototype.open;let once=true;IDBFactory.prototype.open=function(...args:any[]){const r=original.apply(this,args as any);if(once&&args[1]){once=false;r.addEventListener('upgradeneeded',()=>r.transaction!.abort());}return r;};});await p.getByRole('button',{name:'TEST ONLY：请求真实数据库升级',exact:true}).click();await expect(p.getByTestId('upgrade-status')).toContainText('升级失败');expect(await snapshot(p)).toEqual(before);
 const blocker=await context.newPage();await blocker.goto(origin);await blocker.evaluate(async()=>{(window as any).held=await new Promise((ok,no)=>{const r=indexedDB.open('researchhub-synthetic-local-v1');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});});await p.getByRole('button',{name:'TEST ONLY：请求真实数据库升级',exact:true}).click();await expect(p.getByTestId('upgrade-status')).toContainText('阻塞');await expect(p.getByLabel('笔记正文')).toHaveValue('保留唯一输入');await blocker.evaluate(()=>{(window as any).held.close();});await expect(p.getByTestId('upgrade-status')).toContainText('完成');expect(await snapshot(p)).toEqual(before);await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');await p.reload();await expect(p.getByLabel('笔记正文')).toHaveValue('保留唯一输入');
 }finally{try{await capture(context);}finally{await context.close();await stopServer(server);}}
});

test('HDSP 与 ICE 高级语境以及无标题草稿可导出恢复',async()=>{
 const server=await startServer();const context=await launch(resolve(runtime,'profiles',`rescue-context-${Date.now()}`));
 try{const p=await context.newPage();await p.goto(origin);await p.getByRole('button',{name:'初始化合成工作区',exact:true}).click();await expect(p.getByLabel('项目选择')).toBeVisible();
 for(const alias of ['hdsp','ice']){await p.getByLabel('项目选择').selectOption(alias);await p.getByRole('button',{name:'新建 Run',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill(`SYNTHETIC ${alias}`);await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');if(!await p.getByText('高级语境（可选）',{exact:true}).locator('..').getAttribute('open').then(v=>v!==null))await p.getByText('高级语境（可选）',{exact:true}).click();await p.getByLabel(alias==='hdsp'?'仿真配置说明':'实验条件说明').fill('SYNTHETIC 明确保留条件');await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');}
 await p.getByRole('button',{name:'新建 Note',exact:true}).click();await p.getByLabel('笔记正文').fill('无标题的未保存输入');await diagnostics(p);const pack=await download(p);expect(pack.content.objects.map((o:any)=>Object.values(o.context_data))).toEqual([['SYNTHETIC 明确保留条件'],['SYNTHETIC 明确保留条件']]);expect(pack.content.drafts[0].title).toBe('');expect(pack.content.drafts[0].body).toBe('无标题的未保存输入');await preview(p,pack);await expect(p.getByTestId('rescue-preview')).toBeVisible();await expect(p.getByLabel('笔记正文')).toHaveValue('无标题的未保存输入');await p.getByRole('button',{name:'确认恢复到空工作区',exact:true}).click();await expect(p.getByTestId('rescue-error')).toContainText('非空');await expect(p.getByLabel('笔记正文')).toHaveValue('无标题的未保存输入');
 }finally{try{await capture(context);}finally{await context.close();await stopServer(server);}}
});
