'use client';
import {useState} from 'react';
import {Plus} from 'lucide-react';
import type {Field} from '@/lib/fields';
type Criterion={id:string;description:string;provenance:string;status:string;evidence_ids:string[]};
export function CriteriaEditor({name,value,evidenceOptions=[],allowDefinition=true}:{name:string;value:unknown;evidenceOptions?:Field['options'];allowDefinition?:boolean}){
 const [criteria,setCriteria]=useState<Criterion[]>(Array.isArray(value)?value:[]);
 const update=(index:number,patch:Partial<Criterion>)=>setCriteria(rows=>rows.map((c,i)=>i===index?{...c,...patch}:c));
 return <div className="criteria-editor"><input type="hidden" name={name} value={JSON.stringify(criteria)}/>{!allowDefinition&&<small>现有 Gate 的判据定义与 ID 固定；可更新状态与关联 Evidence。</small>}{criteria.map((criterion,index)=><fieldset key={index}><legend>{criterion.id||`Criterion ${index+1}`}</legend><p>{criterion.description}</p><small>Provenance: {criterion.provenance||'unknown'}</small><div className="form-grid"><label className="field"><span>Criterion Status</span><select value={criterion.status??'not_started'} onChange={e=>update(index,{status:e.target.value})}>{['not_started','in_progress','passed','failed','blocked'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="field"><span>Criterion Evidence</span><select multiple value={criterion.evidence_ids??[]} onChange={e=>update(index,{evidence_ids:[...e.target.selectedOptions].map(x=>x.value)})}>{evidenceOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><small>可多选；没有证据时保持空列表。</small></label></div>{allowDefinition&&<details><summary>编辑 criterion 定义（高级）</summary><label className="field"><span>Criterion ID</span><input value={criterion.id} onChange={e=>update(index,{id:e.target.value})}/></label><label className="field"><span>Criterion Description</span><textarea value={criterion.description} onChange={e=>update(index,{description:e.target.value})}/></label><label className="field"><span>Provenance</span><input value={criterion.provenance} onChange={e=>update(index,{provenance:e.target.value})}/></label></details>}</fieldset>)}{allowDefinition&&<button type="button" onClick={()=>setCriteria(rows=>[...rows,{id:`criterion-${rows.length+1}`,description:'新的判据（请展开定义编辑）',provenance:'proposed',status:'not_started',evidence_ids:[]}])}><Plus size={16} aria-hidden/>添加 Criterion</button>}</div>;
}
