'use client';
import {useState} from 'react';
import {Download,Upload} from 'lucide-react';
import {api} from '@/lib/api';
import type {RecordData,ModuleManifest} from '../../../../packages/shared/types';
import {date,Empty,Panel} from './ui';
export function Files({projectId,runId,rows,manifest,onChange}:{projectId:string;runId?:string;rows:RecordData[];manifest:ModuleManifest;onChange:()=>void}){
  const [error,setError]=useState(''),[uploading,setUploading]=useState(false),[show,setShow]=useState(false);
  return <Panel title="Files / Artifacts" action={<button onClick={()=>setShow(!show)}><Upload size={16} aria-hidden/>上传文件</button>}>{show&&<form className="upload-form" onSubmit={async event=>{event.preventDefault();setError('');setUploading(true);const data=new FormData(event.currentTarget);if(runId)data.set('run_id',runId);try{await api(`/projects/${projectId}/artifacts`,{method:'POST',body:data});onChange();setShow(false);}catch(e){setError((e as Error).message);}finally{setUploading(false);}}}><label className="field"><span>文件 / 实验照片</span><input type="file" name="file" required accept=".png,.jpg,.jpeg,.pdf,.csv,.json,.mat,.npy,.npz,.zip,.txt,.log"/></label><label className="field"><span>Category</span><select name="category">{manifest.artifact_categories.map(x=><option key={x}>{x}</option>)}</select></label>{!runId&&<label className="field"><span>Run ID（可选）</span><input name="run_id"/></label>}<label className="field"><span>Metadata（JSON，可选）</span><input name="metadata" defaultValue="{}"/></label><button className="primary" disabled={uploading}>{uploading?'正在上传…':'上传至 Object Storage'}</button></form>}{error&&<p className="error" role="alert">{error}</p>}{!rows.length?<Empty>尚无 Artifact。文件字节进入 MinIO，数据库保留元数据与 checksum。</Empty>:<div className="table-scroll"><table><thead><tr><th>文件</th><th>Category</th><th>大小</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{String(row.filename)}</strong><details><summary>Metadata / checksum</summary><dl><dt>SHA-256</dt><dd><code>{String(row.checksum)}</code></dd><dt>Run</dt><dd>{String(row.run_id??'—')}</dd><dt>MIME</dt><dd>{String(row.mime_type)}</dd><dt>Metadata</dt><dd><pre>{JSON.stringify(row.metadata??row.metadata_json,null,2)}</pre></dd></dl></details></td><td>{String(row.category)}</td><td>{(Number(row.size)/1024).toFixed(1)} KB</td><td>{date(row.created_at)}</td><td><a className="button" href={`/api/artifacts/${row.id}/download`}><Download size={16} aria-hidden/>下载</a></td></tr>)}</tbody></table></div>}</Panel>
}
