'use client';
import {useState} from 'react';
import {Download,Upload} from 'lucide-react';
import {api} from '@/lib/api';
import {useData} from '@/lib/use-data';
import type {RecordData,ModuleManifest,QueryPage} from '../../../../packages/shared/types';
import {date,Empty,Panel,human} from './ui';
import {ArtifactControls} from './artifact-controls';
export function Files({projectId,runId,rows,manifest,onChange}:{projectId:string;runId?:string;rows:RecordData[];manifest:ModuleManifest;onChange:()=>void}){
  const tags=useData<QueryPage<RecordData>>(`/projects/${projectId}/tags/query?limit=100`);
  const [error,setError]=useState(''),[uploading,setUploading]=useState(false),[show,setShow]=useState(false);
  return <Panel title="文件与研究产物" action={<button onClick={()=>setShow(!show)}><Upload size={16} aria-hidden/>上传文件</button>}>{show&&<form className="upload-form" onSubmit={async event=>{event.preventDefault();setError('');setUploading(true);const data=new FormData(event.currentTarget);if(runId)data.set('run_id',runId);try{await api(`/projects/${projectId}/artifacts`,{method:'POST',body:data});onChange();setShow(false);}catch(e){setError((e as Error).message);}finally{setUploading(false);}}}><label className="field"><span>文件 / 实验照片</span><input type="file" name="file" required accept=".png,.jpg,.jpeg,.pdf,.csv,.json,.mat,.npy,.npz,.zip,.txt,.log,.mp4,.webm"/></label><label className="field"><span>类别</span><select name="category">{manifest.artifact_categories.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label>{!runId&&<label className="field"><span>研究记录 ID（可选）</span><input name="run_id"/></label>}<label className="field"><span>元数据（JSON，可选）</span><input name="metadata" defaultValue="{}"/></label><button className="primary" disabled={uploading}>{uploading?'正在上传…':"上传至对象存储"}</button></form>}{error&&<p className="error" role="alert">{error}</p>}{!rows.length?<Empty>尚无 研究文件。文件字节进入 MinIO，数据库保留元数据与校验值。</Empty>:<div className="table-scroll"><table><thead><tr><th>文件</th><th>类别</th><th>大小</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{String(row.filename)}</strong><details><summary>元数据与校验值</summary><dl><dt>SHA-256</dt><dd><code>{String(row.checksum)}</code></dd><dt>研究记录</dt><dd>{String(row.run_id??'—')}</dd><dt>MIME</dt><dd>{String(row.mime_type)}</dd><dt>元数据</dt><dd><pre>{JSON.stringify(row.metadata??row.metadata_json,null,2)}</pre></dd></dl></details></td><td>{human(row.category)}</td><td>{(Number(row.size)/1024).toFixed(1)} KB</td><td>{date(row.created_at)}</td><td><a className="button" href={`/api/artifacts/${row.id}/download`}><Download size={16} aria-hidden/>下载</a>{runId&&row.run_id!==runId?<span className="muted">引用原文件 · <a href={`/runs/${row.run_id}`}>查看所属记录</a></span>:<ArtifactControls artifact={row} tags={tags.data?.items??[]} onChange={onChange}/>}</td></tr>)}</tbody></table></div>}</Panel>
}
