'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Plus,Pencil,Trash2} from 'lucide-react';
import {api,post,patch} from '@/lib/api';
import {useData} from '@/lib/use-data';
import {resourceFields,f} from '@/lib/fields';
import type {Project,ModuleManifest,RecordData,ProjectContext} from '../../../../packages/shared/types';
import {Editor,Empty,Feedback,Panel,Status,date,human} from './ui';
import {ActivityList} from './activity';
export function Projects({projects,refresh}:{projects:Project[];refresh:()=>void}) {
 const modules=useData<ModuleManifest[]>('/modules'),[editing,setEditing]=useState<Project|null|undefined>(),[error,setError]=useState('');
 const search=useSearchParams();useEffect(()=>{if(search.get('new'))setEditing(null);},[search]);
 const fields=resourceFields('projects');fields.find(x=>x.key==='module_id')!.options=(modules.data??[]).map(x=>({value:x.id,label:x.name}));fields.find(x=>x.key==='module_id')!.default='generic';
 return <><div className="page-heading"><div><h1>项目</h1><p className="subtitle">共享科研基础能力，保留每个课题的专业工作流。</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={16} aria-hidden/>新建项目</button></div>{error&&<p className="error" role="alert">{error}</p>}<Feedback error={modules.error}/><Panel title="科研项目">{!projects.length?<Empty>尚无项目。创建通用科研、HDSP 或 ICE 声固化项目。</Empty>:<div className="project-list">{projects.map(project=><article key={project.id}><div><Link className="project-name" href={`/projects/${project.id}`}>{project.name}</Link>{project.is_demo&&<span className="demo-label">DEMO / SYNTHETIC</span>}<p>{project.description}</p><div className="row-meta"><span>{modules.data?.find(x=>x.id===project.module_id)?.name??project.module_id}</span><Status value={project.status}/><span>{project.current_stage??"未选择阶段"}</span></div></div><div className="row-actions"><button className="icon-button" aria-label={`编辑 ${project.name}`} onClick={()=>setEditing(project)}><Pencil size={17}/></button><button className="icon-button danger" aria-label={`删除 ${project.name}`} onClick={async()=>{if(prompt(`将项目「${project.name}」移入回收站？输入完整项目名称确认；可在设置的数据管理中恢复。`)!==project.name)return;try{await api(`/projects/${project.id}`,{method:'DELETE'});refresh();}catch(e){setError((e as Error).message);}}}><Trash2 size={17}/></button></div></article>)}</div>}</Panel>{editing!==undefined&&<Editor title={editing?"编辑项目":"新建项目"} fields={fields} item={editing??undefined} onClose={()=>setEditing(undefined)} onSave={async body=>{if(editing)await patch(`/projects/${editing.id}`,body);else await post('/projects',body);refresh();}}/>}</>;
}
export function Home({projects}:{projects:Project[]}){
 const tasks=useData<RecordData[]>('/tasks'),activity=useData<RecordData[]>('/activity');
 const focus=projects.find(x=>x.status==='active')??projects[0];
 return <><div className="page-heading"><div><h1>科研首页</h1><p className="subtitle">项目、研究任务与证据，集中在同一个工作面。</p></div><Link className="button primary" href="/projects?new=1"><Plus size={16} aria-hidden/>新建项目</Link></div><div className="overview-grid"><Panel title="当前关注">{focus?<div className="focus-project"><Link href={`/projects/${focus.id}`}>{focus.name}</Link>{focus.is_demo&&<span className="demo-label">DEMO / SYNTHETIC</span>}<p>{String(focus.current_objective||focus.description||'尚未填写当前目标')}</p><Status value={focus.status}/></div>:<Empty>创建项目后，当前科研目标将显示在这里。</Empty>}</Panel><Panel title="项目" action={<Link href="/projects">查看全部 →</Link>}><div className="compact-list">{projects.length?projects.map(p=><Link href={`/projects/${p.id}`} key={p.id}><div><strong>{p.name}</strong><small>{human(p.module_id)}{p.is_demo?' · DEMO / SYNTHETIC':''}</small></div><Status value={p.status}/></Link>):<Empty>暂无项目。</Empty>}</div></Panel></div><div className="overview-grid"><Panel title="待完成任务" action={<Link href="/tasks">查看全部 →</Link>}><Feedback loading={tasks.loading} error={tasks.error}/><div className="compact-list">{tasks.data?.filter(x=>x.status!=='done').slice(0,6).map(t=><Link href={`/projects/${t.project_id}/tasks`} key={t.id}><div><strong>{String(t.title)}</strong><small>截止 {t.due_date?String(t.due_date).slice(0,10):'—'}</small></div><Status value={t.status}/></Link>)}{tasks.data&&!tasks.data.some(t=>t.status!=='done')&&<Empty>没有未完成任务。</Empty>}</div></Panel><Panel title="最近活动" action={<Link href="/activity">查看全部 →</Link>}><Feedback loading={activity.loading} error={activity.error}/>{activity.data&&<ActivityList rows={activity.data.slice(0,5)}/>}</Panel></div></>;
}
export function GlobalTasks({projects}:{projects:Project[]}) {
 const tasks=useData<RecordData[]>('/tasks'),[projectId,setProjectId]=useState(''),[editing,setEditing]=useState<RecordData|null|undefined>();
 const context=useData<ProjectContext>(projectId?`/projects/${projectId}/context`:null);
 return <><div className="page-heading"><div><h1>任务</h1><p className="subtitle">简单的任务与里程碑，面向实际研究进度。</p></div><button className="primary" disabled={!projects.length} onClick={()=>{setProjectId(projects[0]?.id??'');setEditing(null);}}><Plus size={16} aria-hidden/>新建任务</button></div><Feedback loading={tasks.loading} error={tasks.error}/><Panel title="所有项目任务">{tasks.data?.length?<div className="resource-list">{tasks.data.map(task=><article key={task.id} className="resource-row"><div className="resource-main"><h3>{String(task.title)}</h3><div className="row-meta"><Link href={`/projects/${task.project_id}/tasks`}>{projects.find(x=>x.id===task.project_id)?.name??"项目"}</Link><Status value={task.status}/><span>{human(task.priority)}</span><span>截止 {task.due_date?String(task.due_date).slice(0,10):'—'}</span></div></div><button className="icon-button" aria-label={`编辑 ${task.title}`} onClick={()=>{setProjectId(String(task.project_id));setEditing(task);}}><Pencil size={17}/></button></article>)}</div>:<Empty>暂无任务。</Empty>}</Panel>{editing!==undefined&&<><label className="field editor-project-choice"><span>新任务所属项目</span><select value={projectId} disabled={Boolean(editing)} onChange={e=>setProjectId(e.target.value)}>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{context.data&&<Editor title={editing?"编辑任务":"新建任务"} fields={editing?resourceFields('tasks',context.data,context.data.module):[f('_project',"所属项目",'select',{required:true,default:projectId,options:projects.map(p=>({value:p.id,label:p.name}))}),...resourceFields('tasks',context.data,context.data.module).filter(x=>x.key!=='milestone_id')]} item={editing??undefined} onClose={()=>setEditing(undefined)} onSave={async body=>{if(editing)await patch(`/tasks/${editing.id}`,body);else {const selected=String(body._project);delete body._project;await post(`/projects/${selected}/tasks`,body);}tasks.refresh();}}/>}</>}</>;
}
export function ActivityPage(){const result=useData<RecordData[]>('/activity');return <><div className="page-heading"><div><h1>活动</h1><p className="subtitle">关键写操作的操作方、操作、资源与审计快照。</p></div></div><Feedback loading={result.loading} error={result.error}/><Panel title="活动时间线">{result.data&&<ActivityList rows={result.data}/>}</Panel></>}
