'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {LineagePage,RecordData} from '../../../../packages/shared/types';
import {useData} from '@/lib/use-data';
import {Panel,Feedback,Status,Empty,human} from './ui';
export function lineageDepth(node:RecordData,rows:RecordData[]):number{const seen=new Set([node.id]);let current=node,depth=0;while(current.parent_run_id){const parent=rows.find(r=>r.id===current.parent_run_id);if(!parent||seen.has(parent.id))break;seen.add(parent.id);current=parent;depth++;}return Math.min(depth,8);}
export function lineageOrder(rows:RecordData[]):RecordData[]{const ids=new Set(rows.map(row=>row.id)),seen=new Set<string>(),ordered:RecordData[]=[];function visit(row:RecordData){if(seen.has(row.id))return;seen.add(row.id);ordered.push(row);for(const child of rows.filter(r=>r.parent_run_id===row.id))visit(child);}for(const row of rows.filter(r=>!r.parent_run_id||!ids.has(String(r.parent_run_id))))visit(row);for(const row of rows)visit(row);return ordered;}
export function Lineage({projectId,focusId}:{projectId:string;focusId?:string}){
 const [offset,setOffset]=useState(0),result=useData<LineagePage>(`/projects/${projectId}/lineage?limit=25&offset=${offset}`);
 return <Panel title="研究记录谱系"><p className="section-copy">每条记录保留父记录关系、执行状态与科研结果。分页之外的父记录显示为链接；谱系不表示结果已通过验证。</p><Feedback loading={result.loading} error={result.error}/>{result.data&&(result.data.nodes.length?<div className="lineage-list">{lineageOrder(result.data.nodes).map(node=>{const change=node.parameter_change_summary as {names:string[];total:number}|undefined,externalParent=Boolean(node.parent_run_id)&&!result.data!.nodes.some(n=>n.id===node.parent_run_id);return <article key={node.id} className={node.id===focusId?'lineage-focus':''} style={{'--lineage-depth':lineageDepth(node,result.data!.nodes)} as React.CSSProperties}><div><code>#{node.id.slice(0,8)}</code>{Boolean(node.is_highlighted)&&<span aria-label="已星标"> ★</span>}<h3><Link href={`/runs/${node.id}`}>{String(node.title)}</Link></h3><p>{human(node.run_type)} · <Status value={node.status}/> · <Status value={node.scientific_outcome}/></p>{Boolean(node.parent_run_id)&&<small>{externalParent?'父记录在其他页：':'父记录：'}<Link href={`/runs/${node.parent_run_id}`}>{String(node.parent_run_id).slice(0,8)}</Link></small>}{change&&<small>参数变化 {change.total} 项{change.names.length?` · ${change.names.join('、')}`:''}{change.total>change.names.length?'…':''}</small>}{Boolean(node.changes_from_parent)&&<p>{String(node.changes_from_parent)}</p>}</div></article>;})}</div>:<Empty>尚无研究记录。</Empty>)}<div className="pagination"><span>共 {result.data?.total??'…'} 条{result.data?.truncated?' · 当前为分页片段':''}</span><button disabled={result.loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>上一页</button><button disabled={result.loading||!result.data||offset+result.data.nodes.length>=result.data.total} onClick={()=>setOffset(offset+25)}>下一页</button></div></Panel>;
}
