'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {ModuleManifest,QueryPage,RecordData,ViewDefinition} from '../../../../packages/shared/types';
import {useData} from '@/lib/use-data';
import {metricSeries} from '@/lib/metric-series';
import {Feedback,Empty,Panel} from './ui';
import {PageControls} from './query-browser';
export function MetricTrend({projectId,module,view}:{projectId:string;module:ModuleManifest;view:Partial<ViewDefinition>}){
 const schemas=module.metric_schemas.filter(s=>!view.metric_ids?.length||view.metric_ids.includes(s.id)),[selected,setSelected]=useState(schemas[0]?.id??''),[offset,setOffset]=useState(0),[runType,setRunType]=useState(''),params=new URLSearchParams({metric_ids:selected,limit:'50',offset:String(offset)});
 if(runType)params.set('run_types',runType);else if(view.run_types?.length)params.set('run_types',view.run_types.join(','));
 const result=useData<QueryPage<RecordData>>(selected?`/projects/${projectId}/metrics/query?${params}`:null),groups=metricSeries(result.data?.items??[]),valid=groups.reduce((n,g)=>n+g.points.length,0),schema=schemas.find(s=>s.id===selected);
 return <Panel title="指标时间序列"><div className="query-toolbar"><label className="field"><span>指标</span><select value={selected} onChange={e=>{setSelected(e.target.value);setOffset(0);}}>{schemas.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="field"><span>记录类型</span><select value={runType} onChange={e=>{setRunType(e.target.value);setOffset(0);}}><option value="">模块视图范围</option>{module.run_types.filter(t=>!view.run_types?.length||view.run_types.includes(typeof t==='string'?t:t.id)).map(t=>{const row=typeof t==='string'?{id:t,name:t}:t;return <option key={row.id} value={row.id}>{row.name}</option>;})}</select></label></div><p className="section-copy">按指标保存时间排列，每页最多 50 个记录。不同单位分图；未知值不补零、不插值。时间表示录入时间，状态与适用条件请同时查看，不能据此自动认定最优。</p><Feedback loading={result.loading} error={result.error}/>{!selected&&<Empty>此模块没有声明指标模板；自定义指标可在记录页查看。</Empty>}{result.data&&<>{groups.length?groups.map(group=>{const xs=group.points.map(p=>p.x),ys=group.points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),spanY=maxY-minY||Math.max(Math.abs(maxY)*.1,1);return <figure className="metric-trend" key={JSON.stringify(group.unit)}><figcaption>{schema?.name??selected} · 单位 {group.unit??'未知'} · {group.points.length} 个数值</figcaption><svg role="img" aria-label={`${schema?.name??selected}按录入时间的数值，单位${group.unit??'未知'}`} viewBox="0 0 640 220"><line x1="70" y1="180" x2="600" y2="180"/><line x1="70" y1="25" x2="70" y2="180"/><text x="8" y="35">{maxY.toPrecision(4)}</text><text x="8" y="180">{minY.toPrecision(4)}</text><text x="70" y="207">{new Date(minX).toLocaleDateString('zh-CN')}</text><text x="500" y="207">{new Date(maxX).toLocaleDateString('zh-CN')}</text>{group.points.map(point=><circle key={point.id} cx={maxX===minX?335:70+(point.x-minX)/(maxX-minX)*530} cy={maxY===minY?102:180-(point.y-minY)/spanY*155} r="5"><title>{point.title} · {point.y} · {new Date(point.x).toLocaleString('zh-CN')}</title></circle>)}</svg></figure>}):<Empty>当前页没有带有效数值与时间的指标。</Empty>}<p className="section-copy">当前页 {result.data.items.length-valid} 项未绘制（未知值、非数值或缺少时间）。<Link href={`/projects/${projectId}/compare`}>比较具体记录与来源 →</Link></p></>}<PageControls page={result.data} offset={offset} setOffset={setOffset} loading={result.loading}/></Panel>;
}
