'use client';
import Link from 'next/link';
import type {ProjectContext,RecordData} from '../../../../packages/shared/types';
import {Panel,Status,Empty,human} from './ui';
import {RunList} from './run-list';
import {ActivityList} from './activity';
import {BestMetrics} from './best-metrics';
export function Overview({context}:{context:ProjectContext}) {
 const {project,module,runs,tasks,gates,questions,evidence,risks,decisions}=context;
 const stage=module.research_stages.find(x=>x.id===project.current_stage);
 const openTasks=tasks.filter(x=>x.status!=='done');
 const currentGates=gates.filter(x=>x.status!=='passed');
 const isIce=module.id==='ice-sonocuring',isHdsp=module.id==='hdsp';
 return <><div className="overview-grid"><Panel title={isIce?"项目阶段与关卡":"研究阶段"}><div className="stage-list"><article><span className="stage-dot"/><div><strong>{stage?`${stage.id} · ${stage.name}`:"尚未选择研究阶段"}</strong><p>{stage?.description??"在工作流中设置当前研究阶段。"}</p></div><Status value={project.status}/></article>{currentGates.slice(0,3).map(gate=><article key={gate.id}><span className={`stage-dot ${gate.status==='blocked'?'blocked-dot':''}`}/><div><strong>{String(gate.gate_id)} · {human(gate.name)}</strong><p>{String(gate.description??'')}</p>{Boolean(gate.blocking_reason)&&<p className="blocking">阻塞原因: {String(gate.blocking_reason)}</p>}</div><Status value={gate.status}/></article>)}</div></Panel><Panel title="研究目标与证据边界"><dl className="objective-list"><dt>当前目标</dt><dd>{String(project.current_objective||project.description||'尚未填写研究目标')}</dd><dt>关键研究问题</dt><dd>{questions.length?<ul>{questions.slice(0,3).map(q=><li key={q.id}>{String(q.title)}</li>)}</ul>:<span className="muted">暂无研究问题</span>}</dd><dt>证据边界</dt><dd><div className="boundary">{project.is_demo?"合成输入，未经物理实验验证。":"结论应以关联证据与适用条件为依据。"}</div><p className="muted">{evidence.length} 条证据 · {evidence.filter(x=>x.status==='validated'||x.status==='reproduced').length} 条已验证 / 已复现</p></dd></dl></Panel></div><Panel title="最近研究记录" action={<Link href={`/projects/${project.id}/runs`}>查看全部研究记录 →</Link>}><RunList rows={[...runs].sort((a,b)=>Date.parse(String(b.updated_at??b.created_at))-Date.parse(String(a.updated_at??a.created_at))).slice(0,5)}/></Panel>{isHdsp&&<BestMetrics context={context}/>}<div className="overview-grid"><Panel title="待完成任务" action={<Link href={`/projects/${project.id}/tasks`}>查看全部任务 →</Link>}>{openTasks.length?<div className="compact-list">{openTasks.slice(0,5).map(task=><Link href={`/projects/${project.id}/tasks`} key={task.id}><div><strong>{String(task.title)}</strong><small>{task.due_date?`截止 ${String(task.due_date).slice(0,10)}`:"未设置截止日期"}</small></div><Status value={task.status}/></Link>)}</div>:<Empty>没有未完成任务。</Empty>}</Panel><Panel title={isIce?"未解决风险与阻塞事项":"最近决策"}>{(isIce?risks.filter(x=>x.status==='open'):decisions).length?<div className="compact-list">{(isIce?risks.filter(x=>x.status==='open'):[...decisions].sort((a,b)=>Date.parse(String(b.created_at))-Date.parse(String(a.created_at)))).slice(0,4).map(row=><div key={row.id}><div><strong>{String(row.title)}</strong><small>{String(row.description??row.decision??'')}</small></div><Status value={row.status}/></div>)}</div>:<Empty>{isIce?"尚无未解决风险。":"尚无决策内容。"}</Empty>}</Panel></div><Panel title="最近活动" action={<Link href="/activity">查看全部活动 →</Link>}><ActivityList rows={context.activity.slice(0,5)}/></Panel></>;
}
