'use client';
import Link from 'next/link';
import type {ProjectContext,RecordData} from '../../../../packages/shared/types';
import {Panel,Status,Empty,human} from './ui';
import {RunList} from './run-list';
import {ActivityList} from './activity';
import {BestMetrics} from './best-metrics';
export function Overview({context}:{context:ProjectContext}) {
 const {project,module,runs,tasks,gates,questions,evidence,risks,decisions}=context;
 const stage=module.research_stages.find(x=>x.id===project.current_stage);
 const openTasks=tasks.filter(x=>x.status!=='done');
 const currentGates=gates.filter(x=>x.status!=='passed');
 const isIce=module.id==='ice-sonocuring',isHdsp=module.id==='hdsp';
 return <><div className="overview-grid"><Panel title={isIce?'Project Stage & Gates':'Research Stage'}><div className="stage-list"><article><span className="stage-dot"/><div><strong>{stage?`${stage.id} · ${stage.name}`:'尚未选择 Stage'}</strong><p>{stage?.description??'在 Workflow 中设置当前研究阶段。'}</p></div><Status value={project.status}/></article>{currentGates.slice(0,3).map(gate=><article key={gate.id}><span className={`stage-dot ${gate.status==='blocked'?'blocked-dot':''}`}/><div><strong>{String(gate.gate_id)} · {String(gate.name)}</strong><p>{String(gate.description??'')}</p>{Boolean(gate.blocking_reason)&&<p className="blocking">Blocking reason: {String(gate.blocking_reason)}</p>}</div><Status value={gate.status}/></article>)}</div></Panel><Panel title="Research Objective & Evidence Boundary"><dl className="objective-list"><dt>Current Objective</dt><dd>{String(project.current_objective||project.description||'尚未填写研究目标')}</dd><dt>Key Questions</dt><dd>{questions.length?<ul>{questions.slice(0,3).map(q=><li key={q.id}>{String(q.title)}</li>)}</ul>:<span className="muted">暂无 Research Question</span>}</dd><dt>Evidence Boundary</dt><dd><div className="boundary">{project.is_demo?'Synthetic inputs; no physical validation.':'结论应以关联 Evidence 与适用条件为依据。'}</div><p className="muted">{evidence.length} 条证据 · {evidence.filter(x=>x.status==='validated'||x.status==='reproduced').length} 条 validated / reproduced</p></dd></dl></Panel></div><Panel title="Recent Runs" action={<Link href={`/projects/${project.id}/runs`}>View all runs →</Link>}><RunList rows={[...runs].sort((a,b)=>Date.parse(String(b.updated_at??b.created_at))-Date.parse(String(a.updated_at??a.created_at))).slice(0,5)}/></Panel>{isHdsp&&<BestMetrics context={context}/>}<div className="overview-grid"><Panel title="Open Tasks" action={<Link href={`/projects/${project.id}/tasks`}>View all tasks →</Link>}>{openTasks.length?<div className="compact-list">{openTasks.slice(0,5).map(task=><Link href={`/projects/${project.id}/tasks`} key={task.id}><div><strong>{String(task.title)}</strong><small>{task.due_date?`Due ${String(task.due_date).slice(0,10)}`:'No due date'}</small></div><Status value={task.status}/></Link>)}</div>:<Empty>没有未完成 Task。</Empty>}</Panel><Panel title={isIce?'Open Risks / Blocking Issues':'Recent Decisions'}>{(isIce?risks.filter(x=>x.status==='open'):decisions).length?<div className="compact-list">{(isIce?risks.filter(x=>x.status==='open'):[...decisions].sort((a,b)=>Date.parse(String(b.created_at))-Date.parse(String(a.created_at)))).slice(0,4).map(row=><div key={row.id}><div><strong>{String(row.title)}</strong><small>{String(row.description??row.decision??'')}</small></div><Status value={row.status}/></div>)}</div>:<Empty>{isIce?'尚无 open risk。':'尚无 Decision。'}</Empty>}</Panel></div><Panel title="Recent Activity" action={<Link href="/activity">View all activity →</Link>}><ActivityList rows={context.activity.slice(0,5)}/></Panel></>;
}
