'use client';
import {zh} from '@/lib/zh';
import Link from 'next/link';
import {useState} from 'react';
import {Plus,Pencil} from 'lucide-react';
import {useData} from '@/lib/use-data';
import {patch} from '@/lib/api';
import {resourceFields,f} from '@/lib/fields';
import type {ProjectContext,ProjectSummary} from '../../../../packages/shared/types';
import {Editor,Feedback,Panel} from './ui';
import {Overview} from './overview';
import {Workflow} from './workflow';
import {Compare} from './compare';
import {DomainView} from './domain-view';
import {DataManagement} from './data-management';
import {QuickRun} from './quick-run';
import {RunBrowser,ResourceBrowser} from './query-browser';
import {ActivityBrowser} from './activity-browser';
import {ProjectTransfer} from './project-transfer';
import {CapabilitySettings} from './capability-settings';
import {moduleNavigation} from '@/lib/module-ui';
import {Lineage} from './lineage';
import {Traceability} from './traceability';
import {QuickCapture} from './quick-capture';
export function ProjectWorkspace({id,tab='overview',onProjectsChange}:{id:string;tab?:string;onProjectsChange:()=>void}){
 const summary=useData<ProjectSummary>(`/projects/${id}/summary`);
 const collections='tags,'+(tab==='research'?'questions,hypotheses,risks,sources':tab==='evidence'?'runs,evidence,claims,sources,artifacts':tab==='tasks'?'milestones':tab==='notes'||tab==='decisions'?'runs,evidence':tab==='workflow'?'gates,evidence':tab==='compare'?'runs':'runs,artifacts,evidence');
 const needsContext=!['overview','runs','files','manage','timeline','transfer','lineage','trace','capture','compare'].includes(tab);
 const result=useData<ProjectContext>(needsContext?`/projects/${id}/context?collections=${collections}&limit=50`:null),[newRun,setNewRun]=useState(false),[editProject,setEditProject]=useState(false);
 if(!summary.data||needsContext&&!result.data)return <Feedback loading={summary.loading||result.loading} error={summary.error||result.error}/>;
 const context:ProjectContext=result.data??{project:summary.data.project,module:summary.data.module,runs:summary.data.recent_runs,tasks:summary.data.current_tasks,milestones:[],questions:[],hypotheses:[],evidence:[],claims:[],sources:[],notes:[],decisions:summary.data.current_decisions,risks:summary.data.current_risks,artifacts:[],gates:summary.data.current_gates,activity:[]};const {project,module}=context;
 const refresh=()=>{result.refresh();summary.refresh();};
 const tabs=moduleNavigation(module).map(v=>[v.id,v.name]);
 const resource=(collection:keyof ProjectContext,title:string)=><ResourceBrowser key={collection} title={title} kind={collection} context={context}/>;
 let content;
 if(tab==='overview')content=<Overview summary={summary.data}/>;
 else if(tab==='research')content=<>{resource('questions',"研究问题")}{resource('hypotheses',"假设")}{resource('risks',"风险")}{resource('sources',"来源")}</>;
 else if(tab==='runs')content=<RunBrowser projectId={id} module={module}/>;
 else if(tab==='compare')content=<Compare context={context}/>;
 else if(tab==='lineage')content=<Lineage projectId={id}/>;
 else if(tab==='trace')content=<Traceability projectId={id}/>;
 else if(tab==='capture')content=<QuickCapture project={project} module={module}/>;
 else if(tab==='tasks')content=<>{resource('tasks',"任务")}{resource('milestones',"里程碑")}</>;
 else if(tab==='evidence')content=<><p className="section-copy">证据状态与适用边界独立保存。科研论断可链接多条证据、研究记录、研究文件 与来源。</p>{resource('evidence',"证据")}{resource('claims',"科研论断")}{resource('sources',"来源")}</>;
 else if(tab==='notes')content=resource('notes',"笔记");
 else if(tab==='decisions')content=resource('decisions',"决策");
 else if(tab==='files')content=resource('artifacts','文件');
 else if(tab==='workflow')content=<Workflow context={context} onChange={result.refresh}/>;
 else if(tab==='manage')content=<><CapabilitySettings project={project} onChange={refresh}/>{resource('tags','项目标签')}<DataManagement project={project} onChange={()=>{refresh();onProjectsChange();}}/></>;
 else if(tab==='timeline')content=<ActivityBrowser projectId={id}/>;
 else if(tab==='transfer')content=<ProjectTransfer projectId={id}/>;
 else content=<DomainView key={`${id}-${tab}-${module.version}`} id={tab} context={context}/>;
 const projectFields=[f('name','项目名称','text',{required:true}),f('description','描述','textarea'),f('current_objective','当前目标','textarea'),f('status','项目状态','select',{options:['active','paused','completed','archived','blocked'].map(value=>({value,label:zh(value)}))}),f('current_stage',"当前阶段",'select',{options:module.research_stages.map(s=>({value:s.id,label:s.name}))})];
 return <><div className="page-heading"><div><div className="title-line"><h1>{project.name}</h1>{project.is_demo&&<span className="demo-label">DEMO / SYNTHETIC</span>}</div><p className="subtitle">{project.description||module.name}</p></div><div className="heading-actions"><button className="icon-button" aria-label="编辑项目" onClick={()=>setEditProject(true)}><Pencil size={17}/></button><button className="primary" onClick={()=>setNewRun(true)}><Plus size={17} aria-hidden/>新建研究记录</button></div></div>{project.is_demo&&<p className="demo-boundary">DEMO / SYNTHETIC · 仅用于验证工作流，不能作为真实科研结果。</p>}<nav className="project-tabs" aria-label="工作区导航">{tabs.map(([key,label])=><Link key={key} className={tab===key?'active':''} href={`/projects/${id}/${key==='overview'?'':key}`}>{label}</Link>)}</nav>{content}{newRun&&<QuickRun project={project} module={module} onClose={()=>setNewRun(false)}/>}{editProject&&<Editor title="编辑项目" fields={projectFields} item={project} onClose={()=>setEditProject(false)} onSave={async body=>{await patch(`/projects/${id}`,body);refresh();onProjectsChange();}}/>}</>;
}
