'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,post} from '@/lib/api';
import type {RecordData} from '../../../../packages/shared/types';
import {Panel} from './ui';
type Preview={preview_id:string;digest:string;run:RecordData;parameters:RecordData[];metrics:RecordData[];artifacts:RecordData[];counts:Record<string,number>;conflicts:{field:string;message:string;path?:string}[];expires_at:string};
export function ProjectTransfer({projectId}:{projectId:string}){
 const [files,setFiles]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[acknowledged,setAcknowledged]=useState(false),router=useRouter();
 return <><Panel title="导出科研记录"><div className="transfer-content"><p>导出项目元数据、Run、参数、指标、证据、论断、决策、来源和完整审计，并附冻结模块定义。</p><label className="checkbox-field"><input type="checkbox" checked={files} onChange={e=>setFiles(e.target.checked)}/>包含研究文件字节（否则只导出元数据）</label><div className="heading-actions"><a className="button primary" href={`/api/projects/${projectId}/export?include_files=${files}`}>下载项目 ZIP</a><a className="button" href={`/api/projects/${projectId}/research-log`}>下载研究日志 Markdown</a></div><small>导出只读取数据；大文件会增加下载时间。</small></div></Panel>
  <Panel title="导入研究 Bundle"><form className="transfer-content" onSubmit={async e=>{e.preventDefault();setError('');setPreview(null);setAcknowledged(false);setBusy(true);try{setPreview(await api<Preview>(`/projects/${projectId}/imports/preview`,{method:'POST',body:new FormData(e.currentTarget)}));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
   <p>选择包含 researchhub-run.json、parameters.json、metrics.json、manifest.json 和 artifacts 文件夹的 ZIP。预览不会创建科研记录。</p><label className="field"><span>研究 Bundle ZIP</span><input type="file" name="file" accept=".zip" required/></label><button disabled={busy}>{busy?'正在验证…':'验证并预览'}</button>
  </form>{preview&&<div className="transfer-content"><h3>{String(preview.run.title)}</h3><dl className="record-dl"><dt>研究类型</dt><dd>{String(preview.run.run_type)}</dd><dt>研究目标</dt><dd>{String(preview.run.objective??'未填写')}</dd><dt>内容数量</dt><dd>{Object.entries(preview.counts).map(([key,n])=>`${({parameters:'参数',metrics:'指标',artifacts:'文件'} as Record<string,string>)[key]??key} ${n}`).join(' · ')}</dd></dl>{preview.conflicts.length?<div role="status">{preview.conflicts.map((c,i)=><p key={i}>{c.message}{c.path?` · ${c.path}`:''}</p>)}<label className="checkbox-field"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/>我已核对重复提示，同意创建独立记录</label></div>:<p>未发现冲突。请逐项核对数值、单位、来源和文件校验值后确认。</p>}<details><summary>查看将导入的完整定义</summary><pre>{JSON.stringify({run:preview.run,parameters:preview.parameters,metrics:preview.metrics,artifacts:preview.artifacts},null,2)}</pre></details><button className="primary" disabled={busy||preview.conflicts.length>0&&!acknowledged} onClick={async()=>{setBusy(true);setError('');try{const imported=await post<{run:RecordData}>(`/projects/${projectId}/imports/confirm`,{preview_id:preview.preview_id,digest:preview.digest,confirm:true});router.push(`/runs/${imported.run.id}`);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>确认导入此记录</button></div>}{error&&<p className="error" role="alert">{error}</p>}</Panel>
 </>;
}
