'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Plus,Pencil} from 'lucide-react';
import {useData} from '@/lib/use-data';
import {post,patch} from '@/lib/api';
import {resourceFields,f} from '@/lib/fields';
import type {ProjectContext} from '../../../../packages/shared/types';
import {Editor,Feedback,Panel,ResourceList,Status,Empty} from './ui';
import {Overview} from './overview';
import {Workflow} from './workflow';
import {RunList} from './run-list';
import {Compare} from './compare';
import {Files} from './files';
import {ActivityList} from './activity';
import {DomainView} from './domain-view';
const baseTabs=[['overview','Overview'],['research','Research'],['runs','Runs'],['evidence','Evidence'],['tasks','Tasks'],['files','Files'],['notes','Notes'],['decisions','Decisions'],['workflow','Workflow']];
export function ProjectWorkspace({id,tab='overview',onProjectsChange}:{id:string;tab?:string;onProjectsChange:()=>void}){
 const result=useData<ProjectContext>(`/projects/${id}/context`),[newRun,setNewRun]=useState(false),[editProject,setEditProject]=useState(false);
 if(!result.data)return <Feedback loading={result.loading} error={result.error}/>;
 const context=result.data,{project,module}=context;
 const views=(module.custom_views??[]).map(v=>typeof v==='string'?{id:v,name:v}:{id:v.id,name:(v.name??v.label??v.id).replaceAll('_',' ')});
 const tabs=[...baseTabs,...views.map(v=>[v.id,v.name]),['timeline','Timeline']];
 const resource=(collection:keyof ProjectContext,title:string)=><ResourceList key={collection} title={title} collection={collection} rows={context[collection] as never[]} fields={resourceFields(collection,context,module)} createPath={`/projects/${id}/${collection}`} onChange={result.refresh}/>;
 let content;
 if(tab==='overview')content=<Overview context={context}/>;
 else if(tab==='research')content=<>{resource('questions','Research Questions')}{resource('hypotheses','Hypotheses')}{resource('risks','Risks')}{resource('sources','Sources')}</>;
 else if(tab==='runs')content=<><Panel title="Research Runs" action={<Link href={`/projects/${id}/compare`}>Compare Runs →</Link>}><RunList rows={context.runs}/></Panel></>;
 else if(tab==='compare')content=<Compare context={context}/>;
 else if(tab==='tasks')content=<>{resource('tasks','Tasks')}{resource('milestones','Milestones')}</>;
 else if(tab==='evidence')content=<><p className="section-copy">Evidence 状态与适用边界独立保存。Claim 可链接多条 Evidence、Run、Artifact 与 Source。</p>{resource('evidence','Evidence')}{resource('claims','Claims')}{resource('sources','Sources')}</>;
 else if(tab==='notes')content=resource('notes','Notes');
 else if(tab==='decisions')content=resource('decisions','Decisions');
 else if(tab==='files')content=<Files projectId={id} rows={context.artifacts} manifest={module} onChange={result.refresh}/>;
 else if(tab==='workflow')content=<Workflow context={context} onChange={result.refresh}/>;
 else if(tab==='timeline')content=<Panel title="Project Timeline"><ActivityList rows={context.activity}/></Panel>;
 else content=<DomainView id={tab} context={context}/>;
 const projectFields=[f('name','项目名称','text',{required:true}),f('description','描述','textarea'),f('current_objective','当前目标','textarea'),f('status','项目状态','select',{options:['active','paused','completed','archived','blocked'].map(value=>({value,label:value}))}),f('current_stage','Current Stage','select',{options:module.research_stages.map(s=>({value:s.id,label:s.name}))})];
 return <><div className="page-heading"><div><div className="title-line"><h1>{project.name}</h1>{project.is_demo&&<span className="demo-label">DEMO / SYNTHETIC</span>}</div><p className="subtitle">{project.description||module.name}</p></div><div className="heading-actions"><button className="icon-button" aria-label="编辑项目" onClick={()=>setEditProject(true)}><Pencil size={17}/></button><button className="primary" onClick={()=>setNewRun(true)}><Plus size={17} aria-hidden/>New Run</button></div></div>{project.is_demo&&<p className="demo-boundary">DEMO / SYNTHETIC · 仅用于验证工作流，不能作为真实科研结果。</p>}<nav className="project-tabs" aria-label="Workspace tabs">{tabs.map(([key,label])=><Link key={key} className={tab===key?'active':''} href={`/projects/${id}/${key==='overview'?'':key}`}>{label}</Link>)}</nav>{content}{newRun&&<Editor title="New Research Run" fields={resourceFields('runs',context,module)} onClose={()=>setNewRun(false)} onSave={async body=>{await post(`/projects/${id}/runs`,body);result.refresh();}}/>}{editProject&&<Editor title="编辑 Project" fields={projectFields} item={project} onClose={()=>setEditProject(false)} onSave={async body=>{await patch(`/projects/${id}`,body);result.refresh();onProjectsChange();}}/>}</>;
}
