'use client';
import {zh} from '@/lib/zh';
import Link from 'next/link';
import {useState} from 'react';
import {Plus,Pencil} from 'lucide-react';
import {useData} from '@/lib/use-data';
import {post,patch} from '@/lib/api';
import {resourceFields,f} from '@/lib/fields';
import type {ProjectContext} from '../../../../packages/shared/types';
import {Editor,Feedback,Panel,ResourceList,Status,Empty} from './ui';
import {Overview} from './overview';
import {Workflow} from './workflow';
import {RunList} from './run-list';
import {Compare} from './compare';
import {Files} from './files';
import {ActivityList} from './activity';
import {DomainView} from './domain-view';
const baseTabs=[['overview',"概览"],['research',"研究"],['runs',"研究记录"],['evidence',"证据"],['tasks',"任务"],['files',"文件"],['notes',"笔记"],['decisions',"决策"],['workflow',"工作流"]];
export function ProjectWorkspace({id,tab='overview',onProjectsChange}:{id:string;tab?:string;onProjectsChange:()=>void}){
 const result=useData<ProjectContext>(`/projects/${id}/context`),[newRun,setNewRun]=useState(false),[editProject,setEditProject]=useState(false);
 if(!result.data)return <Feedback loading={result.loading} error={result.error}/>;
 const context=result.data,{project,module}=context;
 const views=(module.custom_views??[]).map(v=>typeof v==='string'?{id:v,name:v}:{id:v.id,name:(v.name??v.label??v.id).replaceAll('_',' ')});
 const tabs=[...baseTabs,...views.map(v=>[v.id,v.name]),['timeline',"时间线"]];
 const resource=(collection:keyof ProjectContext,title:string)=><ResourceList key={collection} title={title} collection={collection} rows={context[collection] as never[]} fields={resourceFields(collection,context,module)} createPath={`/projects/${id}/${collection}`} onChange={result.refresh}/>;
 let content;
 if(tab==='overview')content=<Overview context={context}/>;
 else if(tab==='research')content=<>{resource('questions',"研究问题")}{resource('hypotheses',"假设")}{resource('risks',"风险")}{resource('sources',"来源")}</>;
 else if(tab==='runs')content=<><Panel title="研究记录" action={<Link href={`/projects/${id}/compare`}>比较研究记录 →</Link>}><RunList rows={context.runs}/></Panel></>;
 else if(tab==='compare')content=<Compare context={context}/>;
 else if(tab==='tasks')content=<>{resource('tasks',"任务")}{resource('milestones',"里程碑")}</>;
 else if(tab==='evidence')content=<><p className="section-copy">证据状态与适用边界独立保存。科研论断可链接多条证据、研究记录、研究文件 与来源。</p>{resource('evidence',"证据")}{resource('claims',"科研论断")}{resource('sources',"来源")}</>;
 else if(tab==='notes')content=resource('notes',"笔记");
 else if(tab==='decisions')content=resource('decisions',"决策");
 else if(tab==='files')content=<Files projectId={id} rows={context.artifacts} manifest={module} onChange={result.refresh}/>;
 else if(tab==='workflow')content=<Workflow context={context} onChange={result.refresh}/>;
 else if(tab==='timeline')content=<Panel title="项目时间线"><ActivityList rows={context.activity}/></Panel>;
 else content=<DomainView id={tab} context={context}/>;
 const projectFields=[f('name','项目名称','text',{required:true}),f('description','描述','textarea'),f('current_objective','当前目标','textarea'),f('status','项目状态','select',{options:['active','paused','completed','archived','blocked'].map(value=>({value,label:zh(value)}))}),f('current_stage',"当前阶段",'select',{options:module.research_stages.map(s=>({value:s.id,label:s.name}))})];
 return <><div className="page-heading"><div><div className="title-line"><h1>{project.name}</h1>{project.is_demo&&<span className="demo-label">DEMO / SYNTHETIC</span>}</div><p className="subtitle">{project.description||module.name}</p></div><div className="heading-actions"><button className="icon-button" aria-label="编辑项目" onClick={()=>setEditProject(true)}><Pencil size={17}/></button><button className="primary" onClick={()=>setNewRun(true)}><Plus size={17} aria-hidden/>新建研究记录</button></div></div>{project.is_demo&&<p className="demo-boundary">DEMO / SYNTHETIC · 仅用于验证工作流，不能作为真实科研结果。</p>}<nav className="project-tabs" aria-label="工作区导航">{tabs.map(([key,label])=><Link key={key} className={tab===key?'active':''} href={`/projects/${id}/${key==='overview'?'':key}`}>{label}</Link>)}</nav>{content}{newRun&&<Editor title="新建研究记录" fields={resourceFields('runs',context,module)} onClose={()=>setNewRun(false)} onSave={async body=>{await post(`/projects/${id}/runs`,body);result.refresh();}}/>}{editProject&&<Editor title="编辑项目" fields={projectFields} item={project} onClose={()=>setEditProject(false)} onSave={async body=>{await patch(`/projects/${id}`,body);result.refresh();onProjectsChange();}}/>}</>;
}
