'use client';
import {useDeferredValue,useState} from 'react';
import type {ModuleManifest,ProjectContext,QueryPage,RecordData} from '../../../../packages/shared/types';
import {useData} from '@/lib/use-data';
import {resourceFields} from '@/lib/fields';
import {Panel,Feedback,ResourceList,human} from './ui';
import {RunList} from './run-list';
import {Files} from './files';
import Link from 'next/link';

export function PageControls({page,offset,setOffset,loading}:{page:QueryPage<RecordData>|null;offset:number;setOffset:(n:number)=>void;loading?:boolean}){
 const size=page?.limit??25;return <div className="pagination"><span>{page?`共 ${page.total} 条 · 第 ${Math.floor(offset/size)+1} 页`:'正在检索…'}</span><button disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-size))}>上一页</button><button disabled={loading||!page||offset+page.items.length>=page.total} onClick={()=>setOffset(offset+size)}>下一页</button></div>;
}
export function RunBrowser({projectId,module}:{projectId:string;module:ModuleManifest}){
 const [q,setQ]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[outcome,setOutcome]=useState(''),[highlight,setHighlight]=useState(false),[sort,setSort]=useState('created_at'),[offset,setOffset]=useState(0),[tag,setTag]=useState(''),[after,setAfter]=useState(''),[before,setBefore]=useState(''),[parent,setParent]=useState('');
 const query=useDeferredValue(q),params=new URLSearchParams({limit:'25',offset:String(offset),q:query,sort,direction:'desc'});
 for(const [key,value] of Object.entries({run_type:type,status,scientific_outcome:outcome,tag_id:tag,date_from:after,date_to:before,parent_run_id:parent}))if(value)params.set(key,value);
 if(highlight)params.set('is_highlighted','true');
 const result=useData<QueryPage<RecordData>>(`/projects/${projectId}/runs/query?${params}`),tags=useData<QueryPage<RecordData>>(`/projects/${projectId}/tags/query?limit=100`);
 const change=(fn:()=>void)=>{fn();setOffset(0);};
 return <Panel title="研究记录" action={<Link href={`/projects/${projectId}/compare`}>比较记录 →</Link>}>
  <div className="query-toolbar"><label className="field"><span>搜索标题或目标</span><input value={q} onChange={e=>change(()=>setQ(e.target.value))} type="search"/></label><label className="field"><span>记录类型</span><select value={type} onChange={e=>change(()=>setType(e.target.value))}><option value="">全部类型</option>{module.run_types.map(t=>{const item=typeof t==='string'?{id:t,name:t}:t;return <option key={item.id} value={item.id}>{item.name}</option>;})}</select></label><label className="field"><span>显示范围</span><select value={highlight?'highlighted':'all'} onChange={e=>change(()=>setHighlight(e.target.value==='highlighted'))}><option value="all">全部记录</option><option value="highlighted">只看星标</option></select></label><label className="field"><span>排序</span><select value={sort} onChange={e=>change(()=>setSort(e.target.value))}><option value="created_at">创建时间（最近在前）</option><option value="updated_at">更新时间（最近在前）</option><option value="title">标题</option></select></label></div>
  <details className="query-details"><summary>更多筛选</summary><div className="query-toolbar"><label className="field"><span>运行状态</span><select value={status} onChange={e=>change(()=>setStatus(e.target.value))}><option value="">全部状态</option>{[['planned','计划中'],['running','进行中'],['completed','已完成'],['failed','运行失败'],['cancelled','已取消'],['blocked','受阻']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="field"><span>科研结果</span><select value={outcome} onChange={e=>change(()=>setOutcome(e.target.value))}><option value="">全部结果</option>{[['unknown','未知'],['positive_result','正结果'],['negative_result','负结果'],['inconclusive','暂不确定'],['candidate_rejected','候选否决']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="field"><span>标签</span><select value={tag} onChange={e=>change(()=>setTag(e.target.value))}><option value="">全部标签</option>{tags.data?.items.map(t=><option key={t.id} value={t.id}>{String(t.name)}</option>)}</select></label><label className="field"><span>父记录 ID</span><input value={parent} onChange={e=>change(()=>setParent(e.target.value))}/></label><label className="field"><span>开始日期</span><input type="date" value={after} onChange={e=>change(()=>setAfter(e.target.value))}/></label><label className="field"><span>结束日期</span><input type="date" value={before} onChange={e=>change(()=>setBefore(e.target.value))}/></label></div></details>
  <Feedback loading={result.loading} error={result.error}/>{result.data&&<RunList rows={result.data.items} onChange={result.refresh}/>}<PageControls page={result.data} offset={offset} setOffset={setOffset} loading={result.loading}/>
 </Panel>;
}
export function ResourceBrowser({kind,title,context}:{kind:keyof ProjectContext;title:string;context:ProjectContext}){
 const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[status,setStatus]=useState(''),[run,setRun]=useState(''),[category,setCategory]=useState(''),[after,setAfter]=useState(''),[before,setBefore]=useState(''),[tag,setTag]=useState(''),[evidenceType,setEvidenceType]=useState(''),[mime,setMime]=useState('');const deferred=useDeferredValue(q);
 const params=new URLSearchParams({limit:'25',offset:String(offset),q:deferred,sort:'updated_at',direction:'desc'});
 for(const [key,value] of Object.entries({status,run_id:run,category,date_from:after,date_to:before,tag_id:tag,evidence_type:evidenceType,mime_type:mime}))if(value)params.set(key,value);
 const result=useData<QueryPage<RecordData>>(`/projects/${context.project.id}/${kind}/query?${params}`);
 const tags=useData<QueryPage<RecordData>>(`/projects/${context.project.id}/tags/query?limit=100`);
 const change=(fn:()=>void)=>{fn();setOffset(0);};
 return <><div className="query-toolbar"><label className="field"><span>搜索{title}</span><input type="search" value={q} onChange={e=>change(()=>setQ(e.target.value))}/></label>{['evidence','tasks','decisions'].includes(kind)&&<label className="field"><span>状态</span><select value={status} onChange={e=>change(()=>setStatus(e.target.value))}><option value="">全部状态</option>{(kind==='evidence'?['proposed','unknown','hypothesis','assumed','synthetic','simulated','measured','calibrated','validated','reproduced','rejected']:kind==='tasks'?['todo','doing','blocked','done']:['proposed','accepted','superseded','rejected']).map(v=><option value={v} key={v}>{human(v)}</option>)}</select></label>}{['evidence','artifacts','notes','decisions'].includes(kind)&&<label className="field"><span>关联记录 ID</span><input value={run} onChange={e=>change(()=>setRun(e.target.value))}/></label>}{kind==='artifacts'&&<label className="field"><span>文件类别</span><select value={category} onChange={e=>change(()=>setCategory(e.target.value))}><option value="">全部类别</option>{context.module.artifact_categories.map(x=><option value={x} key={x}>{human(x)}</option>)}</select></label>}{kind==='evidence'&&<label className="field"><span>证据类型</span><select value={evidenceType} onChange={e=>change(()=>setEvidenceType(e.target.value))}><option value="">全部类型</option>{['simulation','measurement','literature','artifact','observation','other'].map(v=><option key={v} value={v}>{human(v)}</option>)}</select></label>}{kind==='artifacts'&&<label className="field"><span>MIME 类型</span><input value={mime} placeholder="image/png" onChange={e=>change(()=>setMime(e.target.value))}/></label>}{['evidence','artifacts','notes','decisions','tasks'].includes(kind)&&<label className="field"><span>标签</span><select value={tag} onChange={e=>change(()=>setTag(e.target.value))}><option value="">全部标签</option>{tags.data?.items.map(t=><option key={t.id} value={t.id}>{String(t.name)}</option>)}</select></label>}<label className="field"><span>开始日期</span><input type="date" value={after} onChange={e=>change(()=>setAfter(e.target.value))}/></label><label className="field"><span>结束日期</span><input type="date" value={before} onChange={e=>change(()=>setBefore(e.target.value))}/></label></div>
  <Feedback loading={result.loading} error={result.error}/>{result.data&&(kind==='artifacts'?<Files projectId={context.project.id} rows={result.data.items} manifest={context.module} onChange={result.refresh}/>:<ResourceList title={title} collection={kind} rows={result.data.items} fields={resourceFields(kind,context,context.module)} createPath={`/projects/${context.project.id}/${kind}`} onChange={result.refresh}/>)}<PageControls page={result.data} offset={offset} setOffset={setOffset} loading={result.loading}/>
 </>;
}
