'use client';
import {useDeferredValue,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {useData} from '@/lib/use-data';
import {api,post,patch} from '@/lib/api';
import type {Project,ModuleManifest,RecordData,QueryPage} from '../../../../packages/shared/types';
import {Panel,Feedback,human} from './ui';
import {PageControls} from './query-browser';
export function QuickCapture({project,module}:{project:Project;module:ModuleManifest}){
 const search=useSearchParams(),[mode,setMode]=useState(['note','lab','photo','task'].includes(search.get('mode')??'')?search.get('mode')!:'note'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState<{id:string;kind:string}|null>(null),[q,setQ]=useState(''),[selectedType,setSelectedType]=useState(''),[offset,setOffset]=useState(0),deferred=useDeferredValue(q),taskRows=useData<QueryPage<RecordData>>(mode==='task'?`/projects/${project.id}/tasks/query?limit=10&offset=${offset}&q=${encodeURIComponent(deferred)}`:null);
 const enabled=project.enabled_capabilities as string[]??module.default_capabilities??[],labTypes=module.run_types.flatMap(t=>typeof t==='object'&&['lab_experiment','measurement_imaging'].includes(t.capability??'')&&enabled.includes(t.capability??'')?[t]:[]);
 const labType=selectedType||labTypes[0]?.id,form=module.run_forms?.find(f=>f.run_type===labType),supported=new Set((module.context_fields??[]).filter(s=>!form||form.groups.some(g=>g.fields.includes(s.id))).map(s=>s.id));
 return <div className="quick-capture"><Panel title="快速采集" action={<Link href={`/projects/${project.id}`}>返回项目</Link>}><p className="section-copy">先保存当下的观察，来源与细节可稍后补充。</p><div className="capture-modes">{[['note','笔记'],['lab','实验'],['photo','照片 / 视频'],['task','任务状态']].map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>{setMode(key);setSaved(null);setError('');}}>{label}</button>)}</div>{mode==='task'?<><label className="field"><span>搜索任务</span><input type="search" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><Feedback loading={taskRows.loading} error={taskRows.error}/><div className="compact-list">{taskRows.data?.items.map(task=><label className="field" key={task.id}><span>{String(task.title)}</span><select disabled={busy} value={String(task.status)} onChange={async e=>{setBusy(true);setError('');try{await patch(`/tasks/${task.id}`,{status:e.target.value});taskRows.refresh();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{[['todo','待办'],['doing','进行中'],['blocked','受阻'],['done','完成']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>)}</div><PageControls page={taskRows.data} offset={offset} setOffset={setOffset} loading={taskRows.loading}/></>:mode==='lab'&&!labTypes.length?<p className="boundary">当前项目没有启用实验或测量记录类型。请先在数据管理启用相关能力。</p>:<form key={mode} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSaved(null);const data=new FormData(e.currentTarget);try{if(mode==='photo'){const body=new FormData();body.set('file',data.get('file')!);body.set('category',String(data.get('category')));body.set('metadata',JSON.stringify({description:String(data.get('description')??'')}));if(data.get('run_id'))body.set('run_id',String(data.get('run_id')));const file=await api<RecordData>(`/projects/${project.id}/artifacts`,{method:'POST',body});setSaved({id:file.id,kind:'artifacts'});}else if(mode==='note'){const note=await post<RecordData>(`/projects/${project.id}/notes`,{title:String(data.get('title')),content:String(data.get('observation'))});setSaved({id:note.id,kind:'notes'});}else{const run=await post<RecordData>(`/projects/${project.id}/runs`,{title:String(data.get('title')),run_type:String(data.get('run_type')),observation:String(data.get('observation')),objective:String(data.get('objective')??''),context_data:Object.fromEntries(['experiment_date','operator','sample_batch','device','equipment','measurement_conditions'].filter(k=>supported.has(k)).map(k=>[k,String(data.get(k)??'')||null])),status:'planned',scientific_outcome:'unknown'});setSaved({id:run.id,kind:'runs'});}}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
 {mode==='photo'?<><label className="field"><span>拍照或选择照片 / 视频</span><input name="file" type="file" accept="image/png,image/jpeg,video/mp4,video/webm" capture="environment" required/><small>是否调用相机由设备与浏览器决定；文件上限 50 MiB。</small></label><label className="field"><span>文件类别</span><select name="category">{module.artifact_categories.map(c=><option key={c} value={c}>{human(c)}</option>)}</select></label><label className="field"><span>关联记录 ID（可选）</span><input name="run_id"/></label><label className="field"><span>现场说明</span><textarea name="description" rows={3}/></label></>:<><label className="field"><span>标题 *</span><input name="title" required/></label>{mode==='lab'&&<><label className="field"><span>实验类型</span><select name="run_type" value={labType} onChange={e=>setSelectedType(e.target.value)}>{labTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field"><span>实验目标</span><input name="objective"/></label><div className="form-grid">{supported.has('experiment_date')&&<label className="field"><span>实验日期</span><input name="experiment_date" type="date"/></label>}{supported.has('operator')&&<label className="field"><span>操作者</span><input name="operator"/></label>}{supported.has('sample_batch')&&<label className="field"><span>样品批次</span><input name="sample_batch"/></label>}{supported.has('device')&&<label className="field"><span>测量设备</span><input name="device"/></label>}{supported.has('equipment')&&<label className="field"><span>实验设备</span><input name="equipment"/></label>}{supported.has('measurement_conditions')&&<label className="field"><span>测量条件</span><input name="measurement_conditions"/></label>}</div></>}<label className="field"><span>{mode==='lab'?'现场观察':'笔记内容'} *</span><textarea name="observation" rows={5} required/></label></>}
 <button className="primary capture-save" disabled={busy}>{busy?'正在保存…':'保存记录'}</button></form>}{error&&<p className="error" role="alert">{error}</p>}{saved&&<p className="capture-success" role="status">已保存。<Link href={saved.kind==='runs'?`/runs/${saved.id}`:`/projects/${project.id}/${saved.kind==='artifacts'?'files':'notes'}`}>查看记录 →</Link></p>}</Panel></div>;
}
