'use client';
import {useEffect,useRef,useState,useDeferredValue} from 'react';
import Link from 'next/link';
import type {ProjectContext,RecordData,QueryPage,DiffRow} from '../../../../packages/shared/types';
import {useData} from '@/lib/use-data';
import {resourceFields} from '@/lib/fields';
import {ResourceList,Feedback,Panel,Empty,human,date} from './ui';
import {PageControls} from './query-browser';
const tracked=['value','unit','status','source_kind','source_id','source_location','derivation','uncertainty','valid_conditions','is_confirmed','artifact_ids'];
export function ScientificHistory({kind,record,onClose}:{kind:'parameters'|'metrics';record:RecordData;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[offset,setOffset]=useState(0),result=useData<QueryPage<RecordData>>(`/${kind}/${record.id}/history?limit=10&offset=${offset}`);
 useEffect(()=>{dialog.current?.showModal();const node=dialog.current;return()=>node?.close();},[]);
 return <dialog className="editor history-dialog" ref={dialog} onCancel={onClose}><div className="editor-heading"><h2>{human(record.name)} · 修改历史</h2><button onClick={onClose}>关闭</button></div><p className="section-copy">不可变审计记录保存操作人及来源、数值、单位、确认状态和适用条件的变化。</p><Feedback loading={result.loading} error={result.error}/>{result.data?.items.map(event=>{const before=event.before as Record<string,unknown>|null,after=event.after as Record<string,unknown>|null;return <article className="history-event" key={event.id}><h3>{human(event.action)}</h3><p>{date(event.timestamp)} · {human(event.actor_type)} · {String(event.actor??'未知操作人')}</p><div className="table-scroll"><table><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody>{tracked.filter(k=>before&&k in before||after&&k in after).map(k=><tr key={k}><th>{human(k)}</th><td><code>{JSON.stringify(before?.[k]??null)}</code></td><td><code>{JSON.stringify(after?.[k]??null)}</code></td></tr>)}</tbody></table></div></article>;})}<PageControls page={result.data} offset={offset} setOffset={setOffset} loading={result.loading}/></dialog>;
}
export function ScientificValues({runId,kind,context,onChange}:{runId:string;kind:'parameters'|'metrics';context:ProjectContext;onChange:()=>void}){
 const [offset,setOffset]=useState(0),[q,setQ]=useState(''),[history,setHistory]=useState<RecordData|null>(null),deferred=useDeferredValue(q),result=useData<QueryPage<RecordData>>(`/runs/${runId}/${kind}?format=page&limit=25&offset=${offset}&q=${encodeURIComponent(deferred)}`),schemas=kind==='parameters'?context.module.parameter_schemas:context.module.metric_schemas;
 const rows=(result.data?.items??[]).map(x=>({...x,title:`${human(x.name)} = ${x.value==null?'未知':JSON.stringify(x.value)} ${x.unit==null?'（单位未知）':x.unit}`,description:`${human(x.source_kind)} · ${String(x.source_location??'来源位置未知')} · 不确定度：${x.uncertainty??'未知'} · 适用条件：${x.valid_conditions??'未知'}${kind==='parameters'?` · ${x.is_confirmed?'已人工确认':'未确认'}`:''}`}));
 return <><label className="field"><span>搜索{kind==='parameters'?'参数':'指标'}</span><input value={q} type="search" onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><Feedback loading={result.loading} error={result.error}/>{result.data&&<ResourceList title={kind==='parameters'?'参数与来源':'指标与来源'} collection={kind} rows={rows} fields={resourceFields(kind,context,context.module)} createPath={`/runs/${runId}/${kind}`} onChange={()=>{result.refresh();onChange();}} presets={schemas.map(s=>({label:`${s.name} · ${s.id}`,values:{id:'',name:s.id,value:null,unit:s.unit,...(kind==='parameters'?{value_type:s.value_type,source_kind:'unknown',is_confirmed:false}:{metric_schema_id:s.id,status:'unknown',source_kind:'unknown'})}}))} actions={row=><><button onClick={()=>setHistory(row)}>历史</button><Link className="button" href={`/projects/${context.project.id}/trace?kind=${kind}&id=${row.id}`}>追踪</Link></>}/>}<PageControls page={result.data} offset={offset} setOffset={setOffset} loading={result.loading}/>{history&&<ScientificHistory kind={kind} record={history} onClose={()=>setHistory(null)}/>}</>;
}
export function RunDiff({runId,otherRunId,kind}:{runId:string;otherRunId?:string;kind:'parameters'|'metrics'}){
 const [offset,setOffset]=useState(0),params=new URLSearchParams({kind,limit:'25',offset:String(offset)});if(otherRunId)params.set('other_run_id',otherRunId);
 const result=useData<QueryPage<DiffRow>>(`/runs/${runId}/diff?${params}`);
 return <Panel title={kind==='parameters'?'参数差异':'指标差异'}><p className="section-copy">按名称比较完整数据库记录；左侧为参考记录，右侧为当前记录。来源、单位及适用条件也参与比较。</p><Feedback loading={result.loading} error={result.error}/>{result.data&&(result.data.items.length?<div className="table-scroll"><table><thead><tr><th>名称</th><th>变化</th><th>参考记录 → 当前记录</th></tr></thead><tbody>{result.data.items.map(row=><tr key={row.name}><th>{human(row.name)}</th><td>{human(row.change_type)}</td><td>{Object.entries(row.fields).map(([field,value])=><div key={field}><strong>{human(field)}：</strong><code>{JSON.stringify(value.parent)} → {JSON.stringify(value.current)}</code></div>)}</td></tr>)}</tbody></table></div>:<Empty>没有差异。</Empty>)}<PageControls page={result.data as QueryPage<RecordData>|null} offset={offset} setOffset={setOffset} loading={result.loading}/></Panel>;
}
