'use client';
import {useState} from 'react';
import {post} from '@/lib/api';
import {Panel} from './ui';
import {PwaControls} from './pwa';
import type {AuthResponse} from '../../../../packages/shared/types';
export function SettingsPage({auth,onLogout,onSeed}:{auth:AuthResponse;onLogout:()=>void;onSeed:()=>void}){
 const [token,setToken]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <><div className="page-heading"><div><h1>Settings</h1><p className="subtitle">个人账号、独立部署与自动化访问。</p></div></div><Panel title="Account"><div className="settings-section"><strong>{auth.user.display_name}</strong><p>{auth.user.email}</p><button onClick={async()=>{try{await post('/auth/logout',{});onLogout();}catch(e){setError((e as Error).message);}}}>退出登录</button></div></Panel><Panel title="MCP / Automation Token"><form className="settings-section" onSubmit={async event=>{event.preventDefault();setError('');setBusy(true);const data=new FormData(event.currentTarget);try{const response=await post<{token:string}>('/auth/tokens',{name:data.get('name'),actor_type:data.get('actor_type'),scopes:data.has('write')?['research:read','research:write']:['research:read']});setToken(response.token);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>默认只读。仅为需要回写科研记录的自动化开启写权限。Token 仅显示一次，服务端只保存摘要。</p><label className="field"><span>Token name</span><input name="name" required/></label><label className="field"><span>Actor type</span><select name="actor_type"><option value="codex">Codex</option><option value="chatgpt">ChatGPT</option></select></label><label className="checkbox-label"><input type="checkbox" name="write"/>允许 research:write</label><button className="primary" disabled={busy}>{busy?'正在创建…':'创建 Token'}</button>{token&&<div className="token-output"><p>请保存此 Token。关闭页面后无法再次获取。</p><textarea aria-label="Automation token" readOnly value={token}/><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(token);setMessage('Token 已复制。');}catch{setMessage('浏览器不允许复制，请从文本框复制。');}}}>复制 Token</button><button type="button" onClick={()=>setToken('')}>隐藏 Token</button></div>}</form></Panel><Panel title="PWA / Mobile"><div className="settings-section"><PwaControls/></div></Panel><Panel title="Demo Workspace"><div className="settings-section"><p>显式建立 Generic / HDSP / ICE 示例。所有项目与结果均持续标记 DEMO / SYNTHETIC。</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await post('/demo/seed',{});onSeed();setMessage('Demo 项目已建立 / 已存在。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>建立 DEMO / SYNTHETIC 数据</button></div></Panel>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</>;
}
