'use client';
import {useState} from 'react';
import {post} from '@/lib/api';
import {Panel} from './ui';
import {PwaControls} from './pwa';
import type {AuthResponse} from '../../../../packages/shared/types';
export function SettingsPage({auth,onLogout,onSeed}:{auth:AuthResponse;onLogout:()=>void;onSeed:()=>void}){
 const [token,setToken]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <><div className="page-heading"><div><h1>设置</h1><p className="subtitle">个人账号、独立部署与自动化访问。</p></div></div><Panel title="账号"><div className="settings-section"><strong>{auth.user.display_name}</strong><p>{auth.user.email}</p><button onClick={async()=>{try{await post('/auth/logout',{});onLogout();}catch(e){setError((e as Error).message);}}}>退出登录</button></div></Panel><Panel title="MCP 与自动化令牌"><form className="settings-section" onSubmit={async event=>{event.preventDefault();setError('');setBusy(true);const data=new FormData(event.currentTarget);try{const response=await post<{token:string}>('/auth/tokens',{name:data.get('name'),actor_type:data.get('actor_type'),scopes:data.has('write')?['research:read','research:write']:['research:read']});setToken(response.token);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>默认只读。仅为需要回写科研记录的自动化开启写权限。令牌仅显示一次，服务端只保存摘要。</p><label className="field"><span>令牌名称</span><input name="name" required/></label><label className="field"><span>操作方类型</span><select name="actor_type"><option value="codex">Codex</option><option value="chatgpt">ChatGPT</option></select></label><label className="checkbox-label"><input type="checkbox" name="write"/>允许写入科研记录（research:write）</label><button className="primary" disabled={busy}>{busy?'正在创建…':"创建令牌"}</button>{token&&<div className="token-output"><p>请保存此令牌。关闭页面后无法再次获取。</p><textarea aria-label="自动化令牌" readOnly value={token}/><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(token);setMessage("令牌已复制。");}catch{setMessage('浏览器不允许复制，请从文本框复制。');}}}>复制令牌</button><button type="button" onClick={()=>setToken('')}>隐藏令牌</button></div>}</form></Panel><Panel title="PWA 与移动访问"><div className="settings-section"><PwaControls/></div></Panel><Panel title="演示工作区"><div className="settings-section"><p>建立通用科研 / HDSP / ICE 示例。所有项目与结果均持续标记 DEMO / SYNTHETIC。</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await post('/demo/seed',{});onSeed();setMessage("演示项目已建立 / 已存在。");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>建立 DEMO / SYNTHETIC 数据</button></div></Panel>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</>;
}
