'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Atom,Home,Folder,ClipboardList,Activity,Settings,User,Plus} from 'lucide-react';
import type {Project} from '../../../../packages/shared/types';
import type {ReactNode} from 'react';
const nav=[{label:'Home',href:'/',icon:Home},{label:'Projects',href:'/projects',icon:Folder},{label:'Tasks',href:'/tasks',icon:ClipboardList},{label:'Activity',href:'/activity',icon:Activity},{label:'Settings',href:'/settings',icon:Settings}];
export function Shell({projects,children,projectId}:{projects:Project[];children:ReactNode;projectId?:string}) {
  const path=usePathname();
  return <div className="app-shell"><a href="#main" className="skip-link">跳转到内容</a><aside className="sidebar"><Link className="brand" href="/"><Atom aria-hidden/><strong>Research Hub</strong><small>v0.1</small></Link><nav aria-label="Global navigation">{nav.map(({label,href,icon:Icon})=><Link key={href} className={path===href||(href==='/projects'&&path.startsWith('/projects/'))?'selected':''} href={href}><Icon aria-hidden/>{label}</Link>)}</nav><div className="sidebar-project-heading"><span>Projects</span><Link href="/projects?new=1" className="icon-button" aria-label="New Project"><Plus size={16}/></Link></div><nav aria-label="Project navigation">{projects.map(project=><Link key={project.id} className={project.id===projectId?'selected':''} href={`/projects/${project.id}`}><Folder aria-hidden/><span>{project.name}</span></Link>)}</nav><p className="sidebar-foot">Personal research workspace<br/>数据独立存储 · v0.1</p></aside><div className="main-shell"><header className="topbar"><div className="desktop-breadcrumb">Projects{projectId&&<> / <span>{projects.find(x=>x.id===projectId)?.name}</span></>}</div><Link className="brand mobile-brand" href="/"><Atom aria-hidden/><strong>Research Hub</strong><small>v0.1</small></Link><Link className="account" href="/settings"><User aria-hidden size={18}/><span>Account</span></Link></header><div className="mobile-project-selector"><select aria-label="选择项目" value={projectId??''} onChange={event=>{window.location.href=event.target.value?`/projects/${event.target.value}`:'/projects';}}><option value="">所有项目</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><main id="main" className="workspace">{children}</main></div><nav className="bottom-nav" aria-label="Mobile navigation">{nav.slice(0,4).map(({label,href,icon:Icon})=><Link key={href} className={path===href||(href==='/projects'&&Boolean(projectId))?'selected':''} href={href}><Icon aria-hidden/><span>{label}</span></Link>)}</nav></div>;
}
