'use client';
import {useDeferredValue,useState,useEffect} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import type {TraceResult,QueryPage,RecordData} from '../../../../packages/shared/types';
import {useData} from '@/lib/use-data';
import {Panel,Feedback,Status,Empty,human} from './ui';
import {PageControls} from './query-browser';
const labels:Record<string,string>={claims:'科研论断',evidence:'证据',runs:'研究记录',artifacts:'文件',sources:'来源',parameters:'参数',metrics:'指标',gates:'关卡',criteria:'判据',decisions:'决策'};
export function TraceGroups({groups,projectId}:{groups:TraceResult['groups'];projectId:string}){return <div className="trace-grid">{Object.entries(groups).map(([kind,page])=><Panel key={kind} title={`${labels[kind]??kind} · ${page.total}`}><p className="muted">当前显示 {page.items.length} 项{page.total>page.items.length?'，请使用下方翻页查看其他关联。':''}</p>{page.items.length?<div className="compact-list">{page.items.map(row=><Link key={row.id} href={kind==='runs'?`/runs/${row.id}`:kind==='artifacts'?`/projects/${projectId}/trace?kind=artifacts&id=${row.id}`:kind==='gates'||kind==='criteria'?`/projects/${projectId}/workflow`:`/projects/${projectId}/trace?kind=${kind}&id=${row.id}`}><div><strong>{String(row.title??row.name??row.filename??row.description??row.criterion_id??row.id)}</strong><small>{String(row.limitations??row.source_location??row.blocking_reason??'')}</small>{row.value!==undefined&&<code>{row.value==null?'未知':JSON.stringify(row.value)} {String(row.unit??'（单位未知）')}</code>}</div><Status value={row.status??row.source_kind}/></Link>)}</div>:<Empty>没有此类关联。</Empty>}</Panel>)}</div>;}
export function EvidenceImpact({evidenceId,projectId}:{evidenceId:string;projectId:string}){
 const [offset,setOffset]=useState(0),result=useData<{evidence:RecordData;groups:TraceResult['groups']}>(`/evidence/${evidenceId}/impact?limit=10&offset=${offset}`);
 const max=Math.max(0,...Object.values(result.data?.groups??{}).map(p=>p.total));
 return <><p className="boundary">这是只读影响预览。证据降级或移入回收站时，失去有效支持的已通过判据与关卡会重新打开；论断和决策仍由你复核。</p><Feedback loading={result.loading} error={result.error}/>{result.data&&<TraceGroups groups={result.data.groups} projectId={projectId}/>}<div className="pagination"><span>关联组分页</span><button disabled={offset===0||result.loading} onClick={()=>setOffset(Math.max(0,offset-10))}>上一页</button><button disabled={offset+10>=max||result.loading} onClick={()=>setOffset(offset+10)}>下一页</button></div></>;
}
export function Traceability({projectId,initialKind,initialId}:{projectId:string;initialKind?:string;initialId?:string}){
 const search=useSearchParams(),[kind,setKind]=useState(initialKind??search.get('kind')??'claims'),[id,setId]=useState(initialId??search.get('id')??''),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[pickOffset,setPickOffset]=useState(0);
 useEffect(()=>{if(!initialId){setKind(search.get('kind')??'claims');setId(search.get('id')??'');setOffset(0);}},[search,initialId]);
 const deferred=useDeferredValue(q),projectCollections=['claims','evidence','runs','artifacts','sources','decisions'],canPick=projectCollections.includes(kind);
 const picks=useData<QueryPage<RecordData>>(canPick?`/projects/${projectId}/${kind}/query?limit=25&offset=${pickOffset}&q=${encodeURIComponent(deferred)}`:null);
 const result=useData<TraceResult>(id?`/projects/${projectId}/trace/${kind}/${id}?limit=10&offset=${offset}`:null),max=Math.max(0,...Object.values(result.data?.groups??{}).map(p=>p.total));
 return <><Panel title="证据追踪"><p className="section-copy">论断 → 证据 → 研究记录 → 文件与来源。也可从记录、文件、参数或来源反查相关论断和关卡；关联不自动等于验证通过。</p>{!initialId&&<div className="query-toolbar"><label className="field"><span>追踪对象</span><select value={kind} onChange={e=>{setKind(e.target.value);setId('');setOffset(0);setPickOffset(0);}}>{Object.entries(labels).filter(([k])=>k!=='criteria'&&k!=='gates').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{canPick&&<label className="field"><span>搜索对象</span><input value={q} type="search" onChange={e=>{setQ(e.target.value);setPickOffset(0);}}/></label>}<label className="field"><span>对象 ID</span><input value={id} onChange={e=>{setId(e.target.value);setOffset(0);}}/></label></div>}{!id&&canPick&&<><Feedback loading={picks.loading} error={picks.error}/><div className="compact-list">{picks.data?.items.map(row=><button key={row.id} onClick={()=>{setId(row.id);setOffset(0);}}>{String(row.title??row.name??row.filename??row.id)}</button>)}</div><PageControls page={picks.data} offset={pickOffset} setOffset={setPickOffset} loading={picks.loading}/></>}{result.data&&<div className="trace-subject"><strong>{String(result.data.subject.title??result.data.subject.name??result.data.subject.filename??id)}</strong> <Status value={result.data.subject.status??result.data.subject.source_kind}/>{Boolean(result.data.subject.limitations)&&<p>{String(result.data.subject.limitations)}</p>}{kind==='artifacts'&&<a className="button" href={`/api/artifacts/${id}/download`}>下载原文件</a>}</div>}<Feedback loading={result.loading} error={result.error}/></Panel>{result.data&&<><TraceGroups groups={result.data.groups} projectId={projectId}/><div className="pagination"><span>关联组分页 · 每组每页 10 项</span><button disabled={offset===0||result.loading} onClick={()=>setOffset(Math.max(0,offset-10))}>上一页</button><button disabled={offset+10>=max||result.loading} onClick={()=>setOffset(offset+10)}>下一页</button></div>{kind==='evidence'&&<details className="more-details"><summary>降级与删除影响预览</summary><EvidenceImpact evidenceId={id} projectId={projectId}/></details>}</>}</>;
}
