'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {X,Plus,Pencil,Trash2} from 'lucide-react';
import {api,patch,post} from '@/lib/api';
import {type Field,parseFields,localDateTime} from '@/lib/fields';
import {CriteriaEditor} from './criteria-editor';
import type {RecordData} from '../../../../packages/shared/types';
export const human=(value:unknown)=>String(value??'unknown').replaceAll('_',' ');
export const date=(value:unknown)=>value?new Date(String(value)).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
export function Status({value}:{value:unknown}) {const status=String(value??'unknown');return <span className={`status status-${status}`}>{human(status)}</span>;}
export function Empty({children='暂无记录。创建第一条科研记录以开始。'}:{children?:ReactNode}) {return <div className="empty">{children}</div>;}
export function Feedback({loading,error}:{loading?:boolean;error?:string}) {return loading?<p className="empty" role="status">正在加载科研工作区…</p>:error?<p className="error" role="alert">{error}</p>:null;}
export function Panel({title,action,children,className=''}:{title:string;action?:ReactNode;children:ReactNode;className?:string}) {return <section className={`panel ${className}`}><header className="panel-heading"><h2>{title}</h2>{action}</header>{children}</section>;}
function initialValue(field:Field,item?:RecordData){const value=item?.[field.key]??field.default;if(field.kind==='json')return JSON.stringify(value??null,null,2);if(field.kind==='date')return String(value??'').slice(0,10);if(field.kind==='datetime-local')return localDateTime(value);return String(value??'');}
export function Editor({title,fields,item,onSave,onClose}:{title:string;fields:Field[];item?:RecordData;onSave:(body:Record<string,unknown>)=>Promise<void>;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{dialog.current?.showModal();const node=dialog.current;return()=>node?.close();},[]);
  return <dialog ref={dialog} className="editor" onCancel={onClose}><div className="editor-heading"><h2>{title}</h2><button type="button" className="icon-button" aria-label="关闭编辑器" onClick={onClose}><X/></button></div><form onSubmit={async event=>{event.preventDefault();setError('');try{const body=parseFields(fields,event.currentTarget);setSaving(true);await onSave(body);onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}><div className="form-grid">{fields.map(field=>field.kind==='criteria'?<div className="field field-wide" key={field.key}><span>{field.label}</span><CriteriaEditor name={field.key} value={item?.[field.key]??field.default} evidenceOptions={field.options} allowDefinition={!item?.id}/>{field.hint&&<small>{field.hint}</small>}</div>:<label className={`field ${['textarea','multi','json'].includes(field.kind??'')?'field-wide':''}`} key={field.key}><span>{field.label}{field.required&&' *'}</span>{field.kind==='textarea'||field.kind==='json'?<textarea name={field.key} required={field.required} defaultValue={initialValue(field,item)} rows={field.kind==='json'?4:3}/>:field.kind==='select'||field.kind==='multi'?<select name={field.key} required={field.required} multiple={field.kind==='multi'} defaultValue={field.kind==='multi'?(item?.[field.key] as string[]??[]):initialValue(field,item)}>{field.kind!=='multi'&&<option value="">请选择 / unknown</option>}{field.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.kind==='boolean'?<input type="checkbox" name={field.key} defaultChecked={Boolean(item?.[field.key]??field.default)}/>:<input name={field.key} required={field.required} type={field.kind??'text'} defaultValue={initialValue(field,item)}/>} {field.kind==='multi'&&<small>可按 Ctrl / Command 多选；手机使用系统选择器。</small>}{field.hint&&<small>{field.hint}</small>}</label>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="editor-actions"><button type="button" onClick={onClose}>取消</button><button type="submit" className="primary" disabled={saving}>{saving?'正在保存…':'保存'}</button></div></form></dialog>;
}
export function ResourceList({title,collection,rows,fields,createPath,onChange,onSelect,presets}:{title:string;collection:string;rows:RecordData[];fields:Field[];createPath:string;onChange:()=>void;onSelect?:(item:RecordData)=>void;presets?:{label:string;values:RecordData}[]}) {
  const [editing,setEditing]=useState<RecordData|null|undefined>(),[seed,setSeed]=useState<RecordData|undefined>(),[error,setError]=useState('');
  return <Panel title={title} action={<button onClick={()=>{setSeed(undefined);setEditing(null);}}><Plus aria-hidden size={16}/>新建</button>}>{presets&&<label className="field schema-presets"><span>Module Schema</span><select value="" onChange={event=>{const preset=presets[Number(event.target.value)];if(preset){setSeed(preset.values);setEditing(null);}}}><option value="">选择领域字段模板…</option>{presets.map((p,i)=><option value={i} key={p.label}>{p.label}</option>)}</select><small>只预填字段定义；值保持 null、来源保持 unknown。</small></label>}{error&&<p className="error" role="alert">{error}</p>}{!rows.length?<Empty/>:<div className="resource-list">{rows.map(row=><article className="resource-row" key={row.id}><div className="resource-main">{onSelect?<button className="text-button row-title" onClick={()=>onSelect(row)}>{String(row.title||row.name||row.statement||row.id)}</button>:<h3>{String(row.title||row.name||row.statement||row.id)}</h3>}<div className="row-meta"><Status value={row.status??row.evidence_status}/><span>{date(row.updated_at??row.created_at)}</span>{Boolean(row.priority)&&<span>{human(row.priority)}</span>}{Boolean(row.due_date)&&<span>Due {String(row.due_date)}</span>}</div>{Boolean(row.description??row.content??row.reason??row.limitations)&&<p className="row-description">{String(row.description??row.content??row.reason??row.limitations)}</p>}{Boolean(row.blocking_reason)&&<p className="blocking">Blocking reason: {String(row.blocking_reason)}</p>}{collection==='decisions'&&<div className="record-details">{['context','decision','alternatives','run_id','evidence_ids'].map(key=><p key={key}><strong>{human(key)}: </strong>{Array.isArray(row[key])?(row[key] as string[]).join(', '):String(row[key]??'—')}</p>)}</div>}{collection==='claims'&&<p className="row-description">Evidence {(row.evidence_ids as string[]??[]).length} · Runs {(row.run_ids as string[]??[]).length} · Files {(row.artifact_ids as string[]??[]).length} · Sources {(row.source_ids as string[]??[]).length}</p>}</div><div className="row-actions"><button className="icon-button" aria-label={`编辑 ${row.title??row.name??row.statement}`} onClick={()=>setEditing(row)}><Pencil size={16}/></button><button className="icon-button danger" aria-label={`删除 ${row.title??row.name??row.statement}`} onClick={async()=>{if(!confirm('删除这条记录？相关科研链接可能受到影响。'))return;try{await api(`/${collection}/${row.id}`,{method:'DELETE'});onChange();}catch(e){setError((e as Error).message);}}}><Trash2 size={16}/></button></div></article>)}</div>}{editing!==undefined&&<Editor title={`${editing?'编辑':'新建'} ${title}`} fields={fields} item={editing??seed} onClose={()=>{setEditing(undefined);setSeed(undefined);}} onSave={async body=>{if(editing)await patch(`/${collection}/${editing.id}`,body);else await post(createPath,body);onChange();}}/>}</Panel>;
}
