import {ManualSync} from './sync/manual';
import {JoinPanel} from './sync/JoinPanel';
import {BindingPanel} from './sync/BindingPanel';
import {createRoot} from 'react-dom/client';
import {QaShell} from './QaShell';
import {Workbench,type WorkbenchAdapter} from './Workbench';
import {LocalCommandService} from './local/commands';
import {openLocalDatabase} from './local/db';
import {initializeSyntheticWorkspace} from './local/seeds';
const open=()=>openLocalDatabase('researchhub-browser-sync-qa-business-v1');
const adapter:WorkbenchAdapter={recordStatus:object=>new ManualSync(open).recordStatus(object.project_id,object.id),synchronize:project=>new ManualSync(open).cycle(project),commands:new LocalCommandService(open,'researchhub-browser-sync-qa-changes-v1',true),initialize:()=>initializeSyntheticWorkspace(open),sync:true};
if(location.origin!=='http://127.0.0.1:3314')document.body.textContent='拒绝启动：固定隔离地址 http://127.0.0.1:3314';
else createRoot(document.getElementById('root')!).render(<QaShell sync><Workbench adapter={adapter} extension={({refresh,snapshot})=><><JoinPanel refresh={refresh}/><BindingPanel refreshToken={snapshot}/></>}/></QaShell>);
declare const __SYNC_TEST_ONLY__:boolean;
if(__SYNC_TEST_ONLY__)void import('./sync/test-fixture');
if(__SYNC_TEST_ONLY__)void import('./sync/security-test-fixture');
