import {test,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {resolve} from 'node:path';
import {launch,closeBrowser,stopServer} from '../tests/lifecycle';
test('TEST ONLY v2转换：稳定身份、Unicode、父链、中断恢复、CAS与真实IDB中止',async()=>{
 const server=spawn(process.execPath,['scripts/server.mjs'],{env:{...process.env,RH_QA_PROFILE:'sync'},stdio:'pipe'});
 await new Promise<void>((ok,no)=>{server.stdout!.on('data',d=>{if(String(d).includes('QA_READY'))ok();});server.on('exit',c=>no(Error(`server ${c}`)));});
 const profile=resolve('../../storage/runtime/browser-sync-qa/a2/profiles',`wire-${Date.now()}`);let context=await launch(profile);
 try{const p=await context.newPage();await p.goto('http://127.0.0.1:3314');await p.getByRole('button',{name:'初始化合成工作区',exact:true}).click();await p.getByRole('button',{name:'新建 Note',exact:true}).click();await p.getByLabel('标题',{exact:true}).fill('SYNTHETIC Unicode');const body='  中文 🧪 e\u0301\n\tunknown\n';await p.getByRole('textbox',{name:'笔记正文',exact:true}).fill(body);await p.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(p.getByTestId('local-save')).toHaveText('已保存到本机');
 const result=await p.evaluate(async()=>{const q=(window as any).__SYNC_QA_TEST_ONLY__;const before=await q.commands.snapshot();const id=before.operations[0].id;let blocked='';try{await q.normalConvert(id);}catch(e){blocked=String(e);}await q.install();let normalStillBlocked='';try{await q.normalConvert(id);}catch(e){normalStillBlocked=String(e);}let interrupted='';try{await q.convert(id,'afterPrepared');}catch(e){interrupted=String(e);}const prep=(await q.metadata()).find((m:any)=>m.operation_id===id);const final=await q.convert(id);const repeated=await q.convert(id);return {before,after:await q.commands.snapshot(),blocked,normalStillBlocked,interrupted,prep,final,repeated};});
 expect(result.blocked).toContain('TRUST_NOT_VERIFIED');expect(result.normalStillBlocked).toContain('TRUST_NOT_VERIFIED');expect(result.interrupted).toContain('interrupted');expect(result.final.transaction_id).toBe(result.prep.transaction_id);expect(result.final.prepare_id).toBe(result.before.operations[0].id);expect(result.final).toEqual(result.repeated);expect(result.after).toEqual(result.before);expect(result.final.transaction.changes[0].payload.content).toBe(body);
 const update=await p.evaluate(async()=>{const q=(window as any).__SYNC_QA_TEST_ONLY__;const s=await q.commands.snapshot();await q.commands.save({...s.objects[0],body:s.objects[0].body+'后继'});const ss=await q.commands.snapshot();const op=ss.operations.find((o:any)=>o.payload.local_edit_version===2);let failure='';try{await q.convert(op.id,'abortCommit');}catch(e){failure=String(e);}const middle=(await q.metadata()).find((m:any)=>m.operation_id===op.id);const race=await q.race(op.id);const final=await q.convert(op.id);return {failure,middle,final,race};});
 expect(update.race.filter((r:any)=>r.status==='fulfilled')).toHaveLength(1);expect(update.race.filter((r:any)=>r.status==='rejected')).toHaveLength(1);expect(update.failure).toContain('aborted');expect(update.middle.conversion).toBe('PREPARED');expect(update.final.parents).toEqual([result.final.revision]);expect(update.final.dependencies).toEqual([result.final.transaction_id]);expect(update.final.transaction_id).toBe(update.middle.transaction_id);
 const chain=await p.evaluate(async()=>{
  const q=(window as any).__SYNC_QA_TEST_ONLY__;const initial=await q.commands.snapshot();const project=initial.projects.find((x:any)=>x.route_alias==='hdsp');
  let run=await q.commands.save({id:crypto.randomUUID(),project_id:project.id,kind:'Run',local_format_version:1,local_edit_version:0,title:'SYNTHETIC run chain',run_type:project.module_snapshot.run_types[0].id,objective:'',observation:'保留正文',status:'failed',scientific_outcome:'unknown',is_highlighted:false,highlight_type:'',highlight_note:'',context_data:{repository:'合成仓库',config:'合成配置'}});
  const beforePatch=await q.commands.snapshot();let patchRejected='';try{await q.commands.setHighlight(run.id,run.local_edit_version,{is_highlighted:true,highlight_type:'',highlight_note:'',observation:'禁止写正文'});}catch(e){patchRejected=String(e);}if(JSON.stringify(await q.commands.snapshot())!==JSON.stringify(beforePatch))throw Error('rejected star changed IDB objects/operations/audit');if(!patchRejected.includes('仅允许星标字段'))throw Error('star command accepted body');
  run=await q.commands.save({...run,observation:'修改后正文'});await q.commands.setHighlight(run.id,run.local_edit_version,{is_highlighted:true,highlight_type:'',highlight_note:' 🧪 标记 '});
  const snap=await q.commands.snapshot();const ops=snap.operations.filter((x:any)=>x.object_id===run.id).sort((a:any,b:any)=>a.payload.local_edit_version-b.payload.local_edit_version);const mappings=[];for(const op of ops)mappings.push(await q.convert(op.id));
  // Source operations remain immutable. A received baseline change after save must not rebase a pending edit.
  const current=(await q.commands.snapshot()).objects.find((x:any)=>x.id===run.id);await q.commands.save({...current,observation:'待发本地正文'});const pending=(await q.commands.snapshot()).operations.find((x:any)=>x.object_id===run.id&&x.payload.local_edit_version===4);
  const db=await new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('researchhub-browser-sync-qa-business-v1');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});await new Promise<void>((ok,no)=>{const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put({id:`received-heads:${run.id}`,heads:['f'.repeat(64)]});tx.oncomplete=()=>ok();tx.onabort=()=>no(tx.error);});db.close();
  let blocked='';try{await q.convert(pending.id);}catch(e){blocked=String(e);}return {mappings,blocked,snap,after:await q.commands.snapshot()};
 });
 expect(chain.mappings[1].parents).toEqual([chain.mappings[0].revision]);expect(chain.mappings[2].parents).toEqual([chain.mappings[1].revision]);expect(chain.mappings[2].transaction.changes[0].payload).toEqual({is_highlighted:true,highlight_type:'',highlight_note:' 🧪 标记 '});expect(chain.blocked).toContain('saved baseline changed');expect(chain.after.objects.find((o:any)=>o.id===chain.mappings[0].object_id).observation).toBe('待发本地正文');
 await closeBrowser(context);context=await launch(profile);const reopened=await context.newPage();await reopened.goto('http://127.0.0.1:3314');const restored=await reopened.evaluate(async()=>{const q=(window as any).__SYNC_QA_TEST_ONLY__;return q.metadata();});expect(restored.find((m:any)=>m.operation_id===update.final.operation_id)).toEqual(update.final);
 }finally{await closeBrowser(context);await stopServer(server);}
});
