import {safeManualDiagnostic} from '../scripts/network-evidence-reporter';
import {expect,type Page} from '@playwright/test';
export async function manualRoundTrip(b:Page,pc:Page,mark:(stage:string,diagnostic?:string|null)=>void){
 let phase='C_PC_BASELINE_UI';const step=(value:string)=>{phase=value;mark(value);};
 const sync=async(page:Page)=>{try{await page.getByRole('button',{name:'立即同步',exact:true}).click();await expect(page.getByTestId('manual-sync-status')).toContainText('本轮发送',{timeout:60000});}catch(error){try{const diagnostic=page.getByTestId('manual-sync-diagnostic');if(await diagnostic.count())mark(phase,safeManualDiagnostic(await diagnostic.textContent()));}catch{/* Diagnostics must not replace the original failing assertion. */}throw error;}};
 const save=async(page:Page)=>{await page.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(page.getByTestId('local-save')).toHaveText('已保存到本机');};
 const choose=async(page:Page,title:string)=>{await page.locator('button.qa-record').filter({hasText:title}).click();await expect(page.getByLabel('标题',{exact:true})).toHaveValue(title);};
 step('C_PC_BASELINE_UI');await pc.getByRole('button',{name:'新建 Run',exact:true}).click();await pc.getByLabel('标题',{exact:true}).fill('SYNTHETIC C manual Run');await save(pc);
 await pc.getByLabel('观察',{exact:true}).fill('SYNTHETIC PC baseline second save');await save(pc);
 await pc.getByRole('button',{name:'新建 Note',exact:true}).click();await pc.getByLabel('标题',{exact:true}).fill('SYNTHETIC C manual Note');await pc.getByLabel('笔记正文',{exact:true}).fill('SYNTHETIC PC note');await save(pc);
 await sync(pc);await sync(b);await sync(pc);
 await expect(pc.getByTestId('manual-sync-status')).toContainText('已验证对端应用回执 3 条');
 step('C_B_NATIVE_EDIT_UI');await choose(b,'SYNTHETIC C manual Run');step('C_B_READ_BASELINE_RUN');await expect(b.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC PC baseline second save');
 const runId=new URL(b.url()).pathname.split('/').at(-1)!;
 step('C_B_SAVE_RUN');await b.getByLabel('观察',{exact:true}).fill('SYNTHETIC B observation');await save(b);step('C_B_STAR_RUN');await b.getByRole('button',{name:'设为星标',exact:true}).click();await expect(b.getByRole('button',{name:'取消星标',exact:true})).toBeVisible();
 step('C_B_SELECT_NOTE');await choose(b,'SYNTHETIC C manual Note');const noteId=new URL(b.url()).pathname.split('/').at(-1)!;
 step('C_B_SAVE_NOTE_FIRST');await b.getByLabel('笔记正文',{exact:true}).fill('SYNTHETIC B note first');await save(b);step('C_B_SAVE_NOTE_SECOND');await b.getByLabel('笔记正文',{exact:true}).fill('SYNTHETIC B note second');await save(b);
 step('C_B_UNCONFIRMED_BEFORE_SEND');await expect(b.getByTestId('record-sync-peer')).toContainText('尚未确认');
 step('C_B_SEND_PENDING');await sync(b);step('C_B_RELAY_ONLY_ASSERT');await expect(b.getByTestId('record-sync-relay')).toContainText('已存储这次修改');await expect(b.getByTestId('record-sync-peer')).toContainText('尚未确认');
 step('C_PC_APPLY_B_PENDING');await sync(pc);step('C_B_COLLECT_PEER_RECEIPTS');await sync(b);
 step('C_B_PEER_ASSERT');await expect(b.getByTestId('record-sync-peer')).toContainText('已验证该设备应用了这次修改');
 step('C_B_CONFIRMATION_COUNT');await expect(b.getByTestId('manual-sync-status')).toContainText('已验证对端应用回执 4 条');
 step('C_PC_READ_AND_EDIT_UI');await choose(pc,'SYNTHETIC C manual Run');expect(new URL(pc.url()).pathname.split('/').at(-1)).toBe(runId);await expect(pc.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC B observation');await expect(pc.getByRole('button',{name:'取消星标',exact:true})).toBeVisible();
 await pc.getByLabel('观察',{exact:true}).fill('SYNTHETIC PC return');await save(pc);
 await choose(pc,'SYNTHETIC C manual Note');expect(new URL(pc.url()).pathname.split('/').at(-1)).toBe(noteId);await expect(pc.getByLabel('笔记正文',{exact:true})).toHaveValue('SYNTHETIC B note second');
 await pc.getByLabel('笔记正文',{exact:true}).fill('SYNTHETIC PC note return');await save(pc);await sync(pc);
 step('C_CLEAN_EDITOR_REFRESH');await sync(b);await expect(b.getByLabel('笔记正文',{exact:true})).toHaveValue('SYNTHETIC PC note return');await choose(b,'SYNTHETIC C manual Run');await expect(b.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC PC return');
 await sync(pc);await expect(pc.getByTestId('manual-sync-status')).toContainText('已验证对端应用回执 2 条');
 step('C_PC_DIRTY_BASELINE_CAS');await choose(pc,'SYNTHETIC C manual Run');await pc.getByLabel('观察',{exact:true}).fill('SYNTHETIC PC unsaved old baseline');
 await b.getByLabel('观察',{exact:true}).fill('SYNTHETIC B newer remote');await save(b);await expect(b.getByTestId('record-sync-peer')).toContainText('尚未确认');await sync(b);await sync(pc);
 await expect(pc.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC PC unsaved old baseline');
 await pc.getByRole('button',{name:'保存到本机',exact:true}).click();await expect(pc.getByTestId('local-save')).toHaveText('本次修改未保存');
 await pc.getByRole('button',{name:'取消星标',exact:true}).click();await expect(pc.getByTestId('local-save')).toHaveText('本次修改未保存');
 await expect(pc.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC PC unsaved old baseline');
 pc.once('dialog',dialog=>dialog.accept());await choose(pc,'SYNTHETIC C manual Note');await sync(b);
 step('C_DIRTY_EDITOR_PRESERVED');await b.getByLabel('观察',{exact:true}).fill('SYNTHETIC unsaved B input');
 await choose(pc,'SYNTHETIC C manual Run');await pc.getByLabel('观察',{exact:true}).fill('SYNTHETIC newer PC return');await save(pc);await sync(pc);await sync(b);
 await expect(b.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC unsaved B input');await expect(b.getByText('可信记录已更新；未保存的输入已保留，请比较后再保存。',{exact:true})).toBeVisible();
 const receipts=await b.evaluate(async()=>{const db=await new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('researchhub-browser-sync-qa-business-v1');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});try{return await new Promise<any[]>((ok,no)=>{const r=db.transaction('meta').objectStore('meta').getAll();r.onsuccess=()=>ok(r.result.filter(x=>x.id.startsWith('peer-confirmed:')).map(x=>({target:x.target,tx:x.transaction_id,raw:Array.from(x.raw)})));r.onerror=()=>no(r.error);});}finally{db.close();}});
 expect(receipts).toHaveLength(5);expect(new Set(receipts.map(r=>r.tx)).size).toBe(5);expect(receipts.every(r=>r.raw.length>0&&r.target)).toBe(true);
 step('C_DURABLE_NATIVE_PEER_RECEIPTS');
 // Explicit UI discard is exercised only after the dirty-preservation assertions.
 b.once('dialog',dialog=>dialog.accept());await b.getByRole('button',{name:'新建 Run',exact:true}).click();
 await b.getByLabel('标题',{exact:true}).fill('SYNTHETIC B origin Run');await save(b);
 await b.getByLabel('观察',{exact:true}).fill('SYNTHETIC B origin observation');await save(b);
 await b.getByRole('button',{name:'设为星标',exact:true}).click();await expect(b.getByRole('button',{name:'取消星标',exact:true})).toBeVisible();
 const remoteOnlyId=new URL(b.url()).pathname.split('/').at(-1)!;
 await sync(b);await sync(pc);await choose(pc,'SYNTHETIC B origin Run');
 expect(new URL(pc.url()).pathname.split('/').at(-1)).toBe(remoteOnlyId);
 await expect(pc.getByLabel('观察',{exact:true})).toHaveValue('SYNTHETIC B origin observation');await expect(pc.getByRole('button',{name:'取消星标',exact:true})).toBeVisible();
 await expect(pc.getByTestId('record-sync-local')).toContainText('没有本地发送操作');
 await sync(b);await expect(b.getByTestId('record-sync-peer')).toContainText('已验证该设备应用了这次修改');
}
