// 简体中文显示词汇；不改动数据库/API 标识或用户自由文本。
const labels: Record<string,string> = {
  'email':'邮箱','password':'密码','name':'名称','title':'标题','status':'状态','statement':'陈述','description':'描述',
  'value':'数值','value_type':'数值类型','content':'内容','scientific_outcome':'科研结果','module_id':'项目类型',
  'stage_gates':'阶段关卡','gate_criteria':'关卡判据','project':'项目','run':'研究记录','research_runs':'研究记录',
  'api_tokens':'访问令牌','issue_api_token':'签发访问令牌','revoke_api_token':'撤销访问令牌',
  'demo_update_gate':'更新演示关卡','invalidate_gate_evidence':'证据失效，关卡重新受阻',
  'invalidate_criterion_evidence':'证据失效，判据重新检查',
  "Home": "首页",
  "Projects": "项目",
  "Tasks": "任务",
  "Activity": "活动",
  "Settings": "设置",
  "Account": "账号",
  "Global navigation": "全局导航",
  "Project navigation": "项目导航",
  "Mobile navigation": "移动导航",
  "Workspace tabs": "工作区导航",
  "Personal research workspace": "个人科研工作区",
  "New Project": "新建项目",
  "Research Projects": "科研项目",
  "No stage": "未选择阶段",
  "Research Home": "科研首页",
  "Current Focus": "当前关注",
  "Open Tasks": "待完成任务",
  "Recent Activity": "最近活动",
  "View all projects →": "查看全部项目 →",
  "View all tasks →": "查看全部任务 →",
  "View all runs →": "查看全部研究记录 →",
  "View all activity →": "查看全部活动 →",
  "View all →": "查看全部 →",
  "New Task": "新建任务",
  "All Project Tasks": "所有项目任务",
  "Activity Timeline": "活动时间线",
  "Overview": "概览",
  "Research": "研究",
  "Runs": "研究记录",
  "Evidence": "证据",
  "Files": "文件",
  "Notes": "笔记",
  "Decisions": "决策",
  "Workflow": "工作流",
  "Timeline": "时间线",
  "Research Questions": "研究问题",
  "Hypotheses": "假设",
  "Risks": "风险",
  "Sources": "来源",
  "Claims": "科研论断",
  "Milestones": "里程碑",
  "Research Runs": "研究记录",
  "Compare Runs →": "比较研究记录 →",
  "Compare Runs": "研究记录比较",
  "Project Timeline": "项目时间线",
  "New Run": "新建研究记录",
  "New Research Run": "新建研究记录",
  "Current Stage": "当前阶段",
  "Research Stage": "研究阶段",
  "Project Stage & Gates": "项目阶段与关卡",
  "Research Objective & Evidence Boundary": "研究目标与证据边界",
  "Current Objective": "当前目标",
  "Key Questions": "关键研究问题",
  "Evidence Boundary": "证据边界",
  "Recent Runs": "最近研究记录",
  "Synthetic inputs; no physical validation.": "合成输入，未经物理实验验证。",
  "Open Risks / Blocking Issues": "未解决风险与阻塞事项",
  "Recent Decisions": "最近决策",
  "Important Metrics / Optimization Progress": "关键指标与优化进度",
  "Run": "研究记录",
  "Metric": "指标",
  "Value": "数值",
  "Evidence status": "证据状态",
  "Name": "名称",
  "Run A": "记录 A",
  "Run B": "记录 B",
  "Difference": "差异",
  "changed": "有变化",
  "same": "相同",
  "Status / Conclusions": "状态与结论",
  "Human Conclusion": "人工结论",
  "Artifacts summary": "文件概况",
  "Parameter Differences": "参数差异",
  "Metric Differences": "指标差异",
  "Probe Architecture": "探头架构",
  "Acoustic Screening": "声学筛选",
  "Beam Steering": "声束偏转",
  "Sequential Scanning": "顺序扫描",
  "Imaging": "成像",
  "k-Wave Validation": "k-Wave 验证",
  "Electroacoustics": "电声特性",
  "Hydrophone Measurement": "水听器测量",
  "Material Response": "材料响应",
  "Thermal / Flow": "热与流动",
  "Dual-function Coexistence": "双功能共存",
  "Tank Validation": "水槽验证",
  "Phantom / Ex-vivo": "模型体与离体验证",
  "Related Evidence": "关联证据",
  "Related Artifacts": "关联文件",
  "Research Context / Gates": "研究背景与关卡",
  "Files / Artifacts": "文件与研究产物",
  "Category": "类别",
  "Metadata / checksum": "元数据与校验值",
  "Metadata": "元数据",
  "Objective / Hypothesis": "目标与假设",
  "Objective": "研究目标",
  "Hypothesis": "研究假设",
  "Protocol": "研究方案",
  "Changes from Parent": "相对父记录的变化",
  "Parameters / Provenance": "参数与来源",
  "Metrics": "指标",
  "Observation / AI Analysis": "观察与 AI 分析",
  "Observation": "观察记录",
  "AI Analysis": "AI 分析",
  "Human Conclusion / Next Step": "人工结论与下一步",
  "Next Step": "下一步",
  "Research Provenance": "研究来源与环境",
  "Environment": "运行环境",
  "Software Version": "软件版本",
  "Code Revision": "代码版本",
  "Started / Completed": "开始与完成时间",
  "Child Runs": "子研究记录",
  "Based on Run": "基于父记录",
  "Run 类型": "研究记录类型",
  "Scientific Outcome": "科研结果",
  "Hypothesis statement": "假设陈述",
  "Research Question": "研究问题",
  "Evidence Status": "证据状态",
  "Milestone": "里程碑",
  "Source Kind": "来源类别",
  "Citation": "文献引用",
  "Evidence Type": "证据类型",
  "Related Run": "关联研究记录",
  "Related Artifact": "关联文件",
  "Related Source": "关联来源",
  "Limitations / evidence boundary": "限制与证据边界",
  "Claim 标题": "论断标题",
  "Claim": "科研论断",
  "Artifacts": "研究文件",
  "Limitations": "适用限制",
  "Context": "决策背景",
  "Decision": "决策内容",
  "Reason": "理由",
  "Alternatives": "备选方案",
  "Mitigation": "缓解措施",
  "Gate ID": "关卡编号",
  "Gate 名称": "关卡名称",
  "Stage": "研究阶段",
  "Criteria / provenance": "判据与来源",
  "Linked Evidence": "关联证据",
  "Blocking Reason": "阻塞原因",
  "Uncertainty": "不确定度",
  "Valid Conditions": "适用条件",
  "Metric Schema": "指标模板",
  "Module Schema": "模块字段模板",
  "Research Stages": "研究阶段",
  "Stage Gates / Criteria": "阶段关卡与判据",
  "Gate Criteria / Evidence": "关卡判据与证据",
  "Provenance": "来源依据",
  "Criterion Status": "判据状态",
  "Criterion Evidence": "判据证据",
  "Criterion ID": "判据编号",
  "Criterion Description": "判据描述",
  "MCP / Automation Token": "MCP 与自动化令牌",
  "Token name": "令牌名称",
  "Actor type": "操作方类型",
  "Automation token": "自动化令牌",
  "PWA / Mobile": "PWA 与移动访问",
  "Demo Workspace": "演示工作区",
  "Email": "邮箱",
  "Generic Research": "通用科研",
  "ICE Sonocuring": "ICE 声固化",
  "Beta": "β 系数",
  "Numerical credibility and acoustic screening": "数值可信度与声学筛选",
  "Imaging evaluation and enhanced simulation": "成像评价与增强仿真",
  "Physical closed-loop validation": "物理闭环验证",
  "System / prototype validation": "系统与原型验证",
  "Pre-animal evidence review": "动物实验前证据评审",
  "Baseline reproducibility": "基线可复现性",
  "Numerical credibility": "数值可信度",
  "Controlled comparison": "受控比较",
  "Deliverable evidence": "可交付证据",
  "Manufacturing / tank validation review": "制造与水槽验证评审",
  "Phantom / ex-vivo validation": "模型体与离体验证",
  "generic": "通用科研",
  "ice-sonocuring": "ICE 声固化",
  "hdsp": "HDSP",
  "codex": "Codex",
  "chatgpt": "ChatGPT",
  "unknown": "未知",
  "active": "进行中",
  "paused": "已暂停",
  "completed": "已完成",
  "archived": "已归档",
  "blocked": "受阻",
  "planned": "计划中",
  "running": "运行中",
  "failed": "失败",
  "cancelled": "已取消",
  "positive_result": "正结果",
  "negative_result": "负结果",
  "inconclusive": "结论不明确",
  "candidate_rejected": "候选已否决",
  "open": "待处理",
  "investigating": "研究中",
  "answered": "已回答",
  "closed": "已关闭",
  "proposed": "拟议",
  "testing": "验证中",
  "supported": "有证据支持",
  "rejected": "已否决",
  "todo": "待开始",
  "doing": "进行中",
  "done": "已完成",
  "low": "低",
  "medium": "中",
  "high": "高",
  "critical": "紧急",
  "not_started": "未开始",
  "in_progress": "进行中",
  "passed": "已通过",
  "hypothesis": "假设",
  "assumed": "假定",
  "synthetic": "合成",
  "simulated": "模拟",
  "measured": "实测",
  "calibrated": "校准",
  "validated": "已验证",
  "reproduced": "已复现",
  "literature": "文献",
  "manufacturer": "厂家",
  "derived": "推导",
  "draft": "草稿",
  "accepted": "已采纳",
  "superseded": "已替代",
  "mitigated": "已缓解",
  "number": "数值",
  "integer": "整数",
  "string": "文本",
  "boolean": "布尔值",
  "object": "对象",
  "array": "数组",
  "simulation": "仿真",
  "measurement": "测量",
  "artifact": "文件",
  "observation": "观察",
  "other": "其他",
  "data": "数据",
  "figure": "图像",
  "report": "报告",
  "protocol": "研究方案",
  "code": "代码",
  "question": "研究问题",
  "design": "研究设计",
  "execution": "研究执行",
  "analysis": "结果分析",
  "review": "复核",
  "target_design": "目标设计",
  "phase_retrieval": "相位检索",
  "phase_plate_design": "相位板设计",
  "acoustic_simulation": "声场仿真",
  "zscan": "轴向扫描",
  "thermal_simulation": "热仿真",
  "curing_prediction": "固化预测",
  "optimization": "优化",
  "physical_validation": "物理验证",
  "numerical_validation": "数值验证",
  "controlled_probe_comparison": "受控探头比较",
  "steering_test": "声束偏转测试",
  "scan_protocol_test": "扫描方案测试",
  "robustness_test": "稳健性测试",
  "imaging_psf": "成像点扩散函数",
  "kwave_validation": "k-Wave 验证",
  "hydrophone_measurement": "水听器测量",
  "material_response": "材料响应",
  "thermal_flow_test": "热与流动测试",
  "prototype_validation": "原型验证",
  "phantom_test": "模型体测试",
  "benchmark": "基准测试",
  "physical_experiment": "物理实验",
  "parameter_sweep": "参数扫描",
  "overview": "概览",
  "research": "研究",
  "runs": "研究记录",
  "evidence": "证据",
  "tasks": "任务",
  "milestones": "里程碑",
  "artifacts": "研究文件",
  "notes": "笔记",
  "decisions": "决策",
  "timeline": "时间线",
  "projects": "项目",
  "questions": "研究问题",
  "hypotheses": "假设",
  "claims": "科研论断",
  "sources": "来源",
  "risks": "风险",
  "tags": "标签",
  "gates": "关卡",
  "parameters": "参数",
  "metrics": "指标",
  "probe_architecture": "探头架构",
  "acoustic_screening": "声学筛选",
  "beam_steering": "声束偏转",
  "sequential_scanning": "顺序扫描",
  "imaging": "成像",
  "electroacoustics": "电声特性",
  "thermal_flow": "热与流动",
  "dual_function_coexistence": "双功能共存",
  "tank_validation": "水槽验证",
  "phantom_ex_vivo": "模型体与离体验证",
  "human": "人工",
  "system": "系统",
  "create": "创建",
  "update": "更新",
  "delete": "删除",
  "create_run": "创建研究记录",
  "upload_artifact": "上传文件",
  "create_token": "创建令牌",
  "revoke_token": "撤销令牌",
  "demo_seed": "生成演示数据",
  "context": "背景",
  "decision": "决策",
  "alternatives": "备选方案",
  "run_id": "关联研究记录",
  "evidence_ids": "关联证据",
  "frequency": "频率",
  "z_target": "目标平面距离",
  "pressure": "声压",
  "algorithm": "算法",
  "iterations": "迭代次数",
  "beta": "β 系数",
  "phase_levels": "相位级数",
  "IoU": "交并比（IoU）",
  "correlation": "相关性",
  "coverage": "覆盖率",
  "p_max": "最大声压",
  "Tmax": "最高温度",
  "Omega": "Arrhenius 积分",
  "best_z": "最优平面",
  "Energy Efficiency": "能量效率",
  "over_cure": "过固化面积",
  "under_cure": "欠固化面积",
  "element_count": "阵元数",
  "pitch": "阵元间距",
  "source_velocity": "声源速度",
  "roi": "评价区域",
  "sound_speed": "声速",
  "dwell_time": "停留时间",
  "material_threshold": "材料响应阈值",
  "leakage": "声学泄漏",
  "outside_threshold_volume": "目标外超阈值体积",
  "outside_peak": "目标外峰值",
  "numerical_sensitivity": "数值敏感性",
  "psf_width": "点扩散函数宽度"
};
export function zh(value:unknown):string {
  const text=String(value??'unknown');
  if(labels[text])return labels[text];
  const action=/^(create|update|delete)_(.+)$/.exec(text);
  if(action)return `${labels[action[1]]}${zh(action[2])}`;
  return text;
}
export function provenanceLabel(value:unknown):string {return zh(value).replace(/^proposed:/,"拟议依据：");}
const errors:Record<string,string>={
  'Authentication required':'请先登录。','Invalid credentials':'邮箱或密码不正确。','Invalid API token':'访问令牌无效。',
  'Token scope does not allow this action':'令牌没有此操作的权限。','CSRF token required':'登录校验已失效，请刷新页面或重新登录。',
  'Human session required for account administration':'账号管理需要本人登录。','Account already initialized':'账号已创建，请登录。',
  'Token not found':'令牌不存在。','Module not found':'模块不存在。','Unknown module':'未知项目模块。','Unknown stage':'未知研究阶段。',
  'Project module cannot change after creation':'创建项目后不能更改模块类型。','Invalid filename':'文件名无效。',
  'Unsupported extension or MIME type':'不支持此文件格式。','Unknown artifact category':'未知文件类别。','Invalid metadata JSON':'元数据需要有效 JSON。',
  'Metadata must be a small JSON object':'元数据应为较小的 JSON 对象。','Empty files are not accepted':'不能上传空文件。',
  'Checksum mismatch':'文件校验值不一致。','Object storage is unavailable':'对象存储暂时不可用。','Upload exceeds configured limit':'文件超过上传大小限制。',
  'File content does not match declared type':'文件内容与声明格式不一致。','Project not found':'项目不存在或无权访问。','Resource not found':'记录不存在或无权访问。',
  'Reference must belong to the same project':'关联记录必须属于同一项目。','Run type is not defined by this module':'此模块未定义该研究记录类型。',
  'Unknown module metric schema':'未知模块指标模板。','Duplicate gate criterion':'关卡判据编号重复。',
  'Existing gate criteria cannot be removed or replaced':'现有关卡判据不能被删除或替换。','Blocked gate requires a reason':'受阻关卡需要填写原因。',
  'Parent run cycle is not allowed':'父子研究记录不能循环关联。','Passed criteria require linked evidence':'通过判据需要关联证据。',
  'Criterion evidence status is insufficient':'判据关联证据的状态不足以支持通过。',
  'Passed gates require all criteria passed and linked evidence':'通过关卡需要全部判据通过并关联证据。',
  'Evidence status is insufficient for gate passage':'关联证据的状态不足以支持关卡通过。',
  'Too many login attempts; retry later':'登录尝试过多，请稍后重试。','value does not match value_type':'数值与所选类型不一致。',
  'Invalid content length':'请求长度无效。','Request body exceeds configured limit':'请求超过大小限制。',
  'Forbidden':'没有操作权限。','Field required':'此项为必填。','Input should be a valid number':'请输入有效数值。',
  'API unavailable':'应用服务暂时不可用。',
  'Input should be a valid integer':'请输入有效整数。','Input should be a valid string':'请输入有效文本。',
};
export function zhError(value:string):string {
  const text=value.replace(/^Value error, /,'');
  if(errors[text])return errors[text];
  if(text.startsWith('String should have at least'))return '输入内容过短，请检查长度。';
  if(text.startsWith('String should have at most'))return '输入内容过长，请缩短内容。';
  if(text.startsWith('Input should be'))return '输入格式或选项不符合要求。';
  return text;
}
